### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#10]
Currently in Wayland a small window is drawn which can be minimised and maximised. Not intended outcome

**Comment by trigg** [comment]
Currently the quickest fix to this is to force the app to work through XWayland

`GDK_BACKEND=X11 discover`

While ideally we would like to have this work natively the idea of a window choosing its own position is against the design of wayland and I'm uncertain if there will be a way to fix this short of attempting to just cover the whole screen. There's also the question of whether input shapes are a thing in wayland.

For now, almost every wayland implementation has xwayland we can rely on

**Comment by trigg** [comment]
As of latest commit we now have first class support for Wayland in any wlroots env. Any bugs on drawing, placement, interactivity etc are now completely valid. Bring it on!
