### ISSUE TITLE
ModuleNotFoundError: No module named 'discover_overlay'

### ISSUE THREAD

**Issue by NightH4nter** [trigg/Discover#101]
The script can't be run:
```
$ ~/.local/bin/discover-overlay
Traceback (most recent call last):
  File "/home/daniel/.local/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
ModuleNotFoundError: No module named 'discover_overlay'
```

And I have no idea, if I should copy-paste anything, because I don't know the location of Discover. The `python-gobject` is installed.

**Comment by trigg** [comment]
What distro and what method did you use to install?

**Comment by NightH4nter** [comment]
Arch, pip.

**Comment by SeerLite** [comment]
Hey, just wanna say I'm also on Arch and installed through pip and it works fine for me.
It's also in `~/.local/bin` and I can run the script directly like in OP or add it to `$PATH` and run normally.
Have you tried uninstalling/reinstalling?

Someone set up an AUR package too: [discover-overlay-git](https://aur.archlinux.org/packages/discover-overlay-git/). Maybe try that one out and see if it works?

**Comment by trigg** [comment]
I'm very confused about this one. Pip should not have this issue. Have you tried installing from git to see if that gets around it?

**Comment by NightH4nter** [comment]
I did, and it didn't work either. I think I messed something up, and I'll most likely be doing clean install soon. Will see if it's gonna work.
