### ISSUE TITLE
Emoji aren't visible

### ISSUE THREAD

**Issue by FourInchKnife** [trigg/Discover#104]
If someone has an emoji in their name, the emojis don't show properly, even if they are generic emoji (I'm not really expecting custom emojis to work)

**Comment by trigg** [comment]
Emoji only show if you have an emoji font installed.

On arch these are
    noto-fonts-emoji
    ttf-joypixels
    ttf-twemoji
    otf-openmoji
    ttf-twemoji-color
    ttf-symbola

**Comment by FourInchKnife** [comment]
Oh ok. Thanks
