### ISSUE TITLE
Rename project to avoid confusion the KDE application store also named Discover

### ISSUE THREAD

**Issue by dpanter** [trigg/Discover#112]
Title says it all really, but again:
Rename project to avoid confusion the KDE application store also named Discover.

**Comment by midget3111** [comment]
We've made steps to change the name to Discover-Overlay. I think the only thing called Discover now is the GitHub project, but there could still be some remnants left over. Everything else is Discover-Overlay. 

We're well aware of the KDE application store, but as the scope of this project is completely different, it's not really an issue.
