### ISSUE TITLE
Doesn't work in private groups

### ISSUE THREAD

**Issue by Pimak** [trigg/Discover#113]
If you create a private discord call, the overlay doesn't work
It is working fine otherwise.

**Comment by trigg** [comment]
This is not a feature that can be added in our current state. We use the StreamKit api and can only use information available in that. This doesn't include private groups or private messages

**Comment by KiitoX** [comment]
Irregardless of support, it would be nice if that was handled gracefully, as it is now a KeyError is thrown and the whole thing needs to be restarted to function afterwards.

**Comment by trigg** [comment]
I wasn't aware it crashed in the process. That's another matter.

**Comment by trigg** [comment]
Partial fix
