### ISSUE TITLE
Cant Select Server or Channel for Text Chat

### ISSUE THREAD

**Issue by Rayqan** [trigg/Discover#117]
I don't seem to be able to select a server or channel under the text tab as they both seem to be grayed out. Everything else seems to work well except for that. Additionally there are not any error messages in the log and discover seems to be able to detect my servers just fine as it is outputting a list of servers I am part of in the log.

**Comment by trigg** [comment]
Is this still present on latest dev version? Not able to reproduce

**Comment by Rayqan** [comment]
I still seem to have the issue, any sort of debug logs I can post? I was able to get it to work by editing the config.ini.

**Comment by trigg** [comment]
what did you edit? The logs should go to standard out, so into terminal as it is running

**Comment by Rayqan** [comment]
I was able to use discord's dev mode to copy the guild and channel ids and enter them under "[text]".

**Comment by Rayqan** [comment]
Additionally I don't see any abnormal messages in the logs, just the expected join/logging in.
