### ISSUE TITLE
Allways show last spoken

### ISSUE THREAD

**Issue by darktweek** [trigg/Discover#119]
Hi !
Good work for this feature, but if you enable the "Display Speaker Only" if no one speak, you have the avatar of the last spoken in red.
Also if you disconnect voice channel this icon stay on.

**Comment by midget3111** [comment]
Is this still an issue?

**Comment by darktweek** [comment]
Don't know, I have switch to windows month a go

**Comment by midget3111** [comment]
As I can't reproduce this, I'm going to close the issue for now.
