### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#12]
Look into whether packaging for various distributions is necessary or not.

**Comment by trigg** [comment]
One option here, as we still have to rely on pip is to actually setup a discord action to distribute this on pip... then the only thing anyone needs to do anywhere is `python -m pip install discover`

From there more people have access as long as they have python.

**Comment by i-need-to-tell-you-something** [comment]
I think from an end-user perspective it would be most convenient if it were **eventually** packaged as Flatpak (on Flathub) or Snap.

Pros:
* Good distro coverage
* Extremely easy installation - GUI access via major software managers. CLI option on par with `pip`.
* Extremely good discoverability - stumble upon it while searching for Discord or other software that is mentioned in this software's description

Cons:
* Takes slightly more disk space probably
* Dev: Need to disable sandboxing or some effort to integrate sandboxing properly
* Dev: Need to package dependencies ??

**Comment by midget3111** [comment]
I think the current implementation of using pip to package seems to be working fairly well. It's simple to use. 
If other wish to implement a flatpak/snap they are free to do so :)

**Comment by midget3111** [comment]
> I think from an end-user perspective it would be most convenient if it were **eventually** packaged as Flatpak (on Flathub) or Snap.
> 
> Pros:
> 
>     * Good distro coverage
> 
>     * Extremely easy installation - GUI access via major software managers. CLI option on par with `pip`.
> 
>     * Extremely good discoverability - stumble upon it while searching for Discord or other software that is mentioned in this software's description
> 
> 
> Cons:
> 
>     * Takes slightly more disk space probably
> 
>     * Dev: Need to disable sandboxing or some effort to integrate sandboxing properly
> 
>     * Dev: Need to package dependencies ??

After a bit of research and consideration (and wanting seem less Steamdeck integration) we're going to look into targeting Flatpak for the next release

**Comment by midget3111** [comment]
Done, I believe.
