### ISSUE TITLE
[Feature Request] Semitransparent background and auto-hide

### ISSUE THREAD

**Issue by vguttmann** [trigg/Discover#122]
Hi there!
I discovered this nice project today. I only would wish for two improvements: 
1. Give the overlay a dark-grey translucent background, so that text is easier to read.
2. Auto-hide the overlay when the mouse is in the vicinity of the overlay. I want my overlay on the left, but that's where the sidebar on ubuntu is.

it would be nice if there was the option to enable those things. Otherwise, keep up the good work!

**Comment by trigg** [comment]
The background colour should already be adjustable. Last I checked it also included semi-transparency on the chooser.

As to autohiding, I'd not considered it. It's worth looking into this

**Comment by trigg** [comment]
On testing it appears the fact we're using input shapes means we receive no mouse motion events. This was to be expected but means we'll be limiting ourselves with this option to X11 only, and forced to poll screen location of mouse and compare to screen location of window. Not ideal.

**Comment by trigg** [comment]
In afterthought and as an idea for next attempt at this - Set the input shape to be equal to xshape and we'd regain mouse motion events, thus allowing us to hide the window. Since we then won't know when the mouse leaves we'd want a 'return after X seconds' setting. This approach would likely work on all supported systems

**Comment by jantap** [comment]
I have a different but similar feature request - different background colors depending on whether someone is speaking (in the windows version of discord the overlay background changes from semitransparent to opaque when someone speaks - i would like to be able to achieve that effect, but preferable customizable). I can't seem to find anything like that in your version. I think I should be able to add that with my limited python knowledge, however I'm unsure of whether you consider it worth merging?

**Comment by trigg** [comment]
I absolutely see the merit of this idea @jantap 

That said I'm content to implement this myself if you are not overly eager to attempt it yourself.

**Comment by jantap** [comment]
@trigg I would like to try my hand as it seems easy enough, and it would be my first open-source contribution. I'll try tomorrow and if my code seems too... well, shit, then you'll just discard it. Would that be okay?
