### ISSUE TITLE
Font rendering problems

### ISSUE THREAD

**Issue by rudha** [trigg/Discover#123]
Changing sizes makes some names blurry, also bold fonts don't show as bold.

How does the font support work? Is there a way to choose font weight?

**Comment by trigg** [comment]
Ah yes, I hadn't considered font weight in my code. I'll look into it!

**Comment by rudha** [comment]
Thanks for the response, I'd take a look too but don't know much python.

**Comment by trigg** [comment]
Issue is...

voice_overlay.py line 380. Default settings for weight and slant as no information is known here
voice_settings.py line 407. Only font family name is extracted from the font chosen, nothing passed or saved about weight or slant

Just documenting for the moment.

**Comment by rudha** [comment]
Tested the latest master and it's been working pretty well, dejavu sans mono bold looks really good at 9.5!

**Comment by trigg** [comment]
Glad to hear! I've been meaning to get back and squash some bugs, feels good man.
