### ISSUE TITLE
Discover fails to get room information when created with TempChannels bot

### ISSUE THREAD

**Issue by Silejonu** [trigg/Discover#128]
When joining a room created with the bot [TempChannels](https://top.gg/bot/555276999669841931), the overlay doesn't show. Quitting and relaunching the overlay works, though.
The terminal reads the following line at the moment of entrance:
`INFO:root:Could not get room`

Here is an example of a Discord server that uses the bot: https://discord.gg/8qCYSMqjhT

**Comment by trigg** [comment]
It looks like this is generally an error for any room created after the overlay starts. From what I see the only option would be to re-poll the guild for a full list of channels after we encounter this problem.
