### ISSUE TITLE
Program launches, but doesn't show icons when people speaking

### ISSUE THREAD

**Issue by sim590** [trigg/Discover#131]
This shows up on stdout:

```
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Autostart info : desktop /home/simon/.local/share/applications/discover_overlay.desktop auto None

(discover-overlay:20270): Gdk-CRITICAL **: 23:03:41.400: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
INFO:root:ID is MY ID
INFO:root:Logged in as USER
INFO:root: MY SERVERS / ROOMS
WARNING:root:Getting 59 rooms

(discover-overlay:20270): Gtk-CRITICAL **: 23:16:32.380: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(discover-overlay:20270): Gtk-CRITICAL **: 23:16:32.397: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

```

So no useful information. It was working fine before some Discord update. Can that be a regression?

**Additional information**

* **Discover version**: 343eb48db858f1b177f170d323740b4c1aa4957f
* **Discord version**:

      Stable 77962 (c886d3c)
      Host 0.0.13
      Linux 64-Bit (5.10.15-Arch1-1)

**Comment by trigg** [comment]
Good Morning!

I'd like to confirm a few details. Does anything show up? Are you only missing the users icons or is nothing displaying on the overlay at all?

Also what is the contents of your config file? (Remove guild/channel from text section if you have them)

**Comment by sim590** [comment]
> I'd like to confirm a few details. Does anything show up? Are you only missing the users icons or is nothing displaying on the overlay at all?

Nothing shows up.

> Also what is the contents of your config file? (Remove guild/channel from text section if you have them)

```
[text]
rightalign = 1
topalign = 2
monitor = None
enabled = 1
floating = 1
floating_x = 0
floating_y = 0
floating_w = 400
floating_h = 400
bg_col = [0.0, 0.0, 0.0, 0.5]
fg_col = [1.0, 1.0, 1.0, 1.0]
popup_style = 0
text_time = 30
show_attach = 1

[main]
rightalign = 0
topalign = 1
bg_col = [0.0, 0.0, 0.0, 0.5]
fg_col = [1.0, 1.0, 1.0, 1.0]
tk_col = [0.0, 0.7, 0.0, 1.0]
mt_col = [0.6, 0.0, 0.0, 1.0]
avatar_size = 48
icon_spacing = 8
text_padding = 6
square_avatar = 0
only_speaking = 1
highlight_self = 0
icon_only = 0
monitor = None
vert_edge_padding = 0
horz_edge_padding = 0
floating = 0
floating_x = 1
floating_y = 373
floating_w = 400
floating_h = 400
order = 0
hi_col = [0.0, 0.0, 0.0, 0.5]
text_baseline_adj = 0

[general]
xshape = 0
```

Weird. I just tested again and now it works... I had issues yesterday. I have not rebooted my computer, but between tries yesterday, I did try several things:

* restart X
* restart gdm
* restart Discord
* restart Discover

and I have tried some of them together, but nothing worked. Now, I can't say why, but it works... I'm sorry that there's nothing useful to add in order to investigate. I'm really clueless as to what's going on since no error message was shown yesterday.

**Comment by trigg** [comment]
If you got no overlay but did get a system-tray icon (assuming you're using a system tray) then it may just have been Discord restart that fixed it.

**Comment by sim590** [comment]
> If you got no overlay but did get a system-tray icon (assuming you're using a system tray) then it may just have been Discord restart that fixed it.

As I said, I did multiple combinations of the attempts I listed above. I did try to restart at the time and it didn't solve it. I just don't know why it now works. I can't confirm. Therefore, I'll close this issue and re-open if the bug comes agains and that I get more information.

Thanks for the follow-up!
