### ISSUE TITLE
Causes loads of `messages` calls

### ISSUE THREAD

**Issue by Mm2PL** [trigg/Discover#134]
Something in the app causes huge amounts of `messages?limit=50` calls, which in turn can get the user rate limited. I found this one the hard way.

# To reproduce
  1. Start Discord, open dev tools, go to network tab.
  2. Start the overlay
  3. Observe the requests flooding in (some can be 429s if you are in enough servers)

**Comment by MrMelon54** [comment]
Yeah I finally figured out that it is this program which causes that after getting rate limited multiple times

**Comment by trigg** [comment]
Not on many servers so I've not been affected by this myself. Looking at it, it seems likely that asking for descriptions of channels causes Discord to poll the servers for new messages instead of replying from cache. 

Speculation aside, I'm looking at this now.

**Comment by MrMelon54** [comment]
oh and how long does an api ban last?

**Comment by MrMelon54** [comment]
oh and I am in 100 server so it bans me almost instantly when I open the program

**Comment by Mm2PL** [comment]
My last api ban lasted for ~40 minutes.

**Comment by trigg** [comment]
https://github.com/trigg/Discover/blob/343eb48db858f1b177f170d323740b4c1aa4957f/discover_overlay/discord_connector.py#L441

So once we're getting a list of Guilds/Servers this is run to work out what channels are in each one. This replies with a list which contains 50-lines of text for each text channel, as well as the voice channel information we actually want.

**Comment by MrMelon54** [comment]
> My last long api ban lasted for ~40 minutes. Most of the `429`s are have retry after at values close to `2s`.

I think my retry after value is in seconds which converted to minutes is `22`

**Comment by trigg** [comment]
Which version of the overlay are you two running?

**Comment by trigg** [comment]
From further research this shouldn't happen at all if the text overlay is disabled.

**Comment by MrMelon54** [comment]
> Which version of the overlay are you two running?

whatever version is the latest on pip

**Comment by MrMelon54** [comment]
> From further research this shouldn't happen at all if the text overlay is disabled.

well i checked the text overlay in the config and it was disabled

**Comment by Mm2PL** [comment]
I run latest from `master` with some unrelated changes to voice stuff.

**Comment by Mm2PL** [comment]
> From further research this shouldn't happen at all if the text overlay is disabled.

It still does happen if it's disabled

<details>
<summary>My config</summary>

`text` -> `enabled` is `0` And yet there is request spam


```ini
[main]
rightalign = 1
topalign = 0
bg_col = [0.0, 0.0, 0.0, 0.5]
fg_col = [1.0, 1.0, 1.0, 1.0]
tk_col = [0.0, 0.7, 0.0, 1.0]
mt_col = [0.75, 0.25, 0.25, 0.847457627118644]
avatar_size = 40
icon_spacing = 6
text_padding = 9
text_baseline_adj = 0
square_avatar = 1
only_speaking = 1
highlight_self = 0
icon_only = 0
monitor = HDMI-2
vert_edge_padding = 32
horz_edge_padding = 4
floating = 0
floating_x = 3438
floating_y = 1
floating_w = 400
floating_h = 400
order = 0
hi_col = [0.0, 0.0, 0.0, 0.5]

[text]
rightalign = 1
topalign = 2
monitor = None
enabled = 0
floating = 1
floating_x = 3561
floating_y = 776
floating_w = 275
floating_h = 280
channel = [private]
guild = [private]
bg_col = [0.0, 0.0, 0.0, 0.5]
fg_col = [1.0, 1.0, 1.0, 1.0]
popup_style = 0
text_time = 30
show_attach = 1
```

</details>

**Comment by trigg** [comment]
'Potentially' fixes.

If this isn't enough then I will simply need to add a disclaimer that this will happen if user is subscribed to too many servers.

**Comment by MrMelon54** [comment]
I didn't even have the text overlay enabled so idk why it was happening to me. Did you fix that as well?

**Comment by trigg** [comment]
This issue is a few issues in one.

The steps in question are :

1) On boot, Discover asks Discord client for a list of all guilds
2) This list returns and we iterate over each guild asking Discord client for channels in it. 

This step is important as otherwise we have no idea what channel the user is in. Once we have a room ID for the user we can request callbacks on talking/leaving/joining

3) Discord client calls out to Discord server to ask for every channel the user can see.
4) Discover requests chat room text for the channel the user has selected

Now the issues are :
- Discord does not cache its information. It knows all guilds and channels, but still requests a fresh copy from Discord server (the real reason we're seeing rate limits)
- When asked for a list of channels Discord client will also request text contents of text rooms. This is not something we can control or opt out of. 
- - Due to this we've now requested 50 lines of text from EVERY text channel the user is in. This is obviously an issue.
- When Discover has text enabled it then requests a copy of text from the channel... As we didn't expect it in the first call we didn't grab it, but now we need it and request it. This is wasteful and should be cut down.

**Comment by MrMelon54** [comment]
So because I'm in 100 servers I instantly cap my Discord api limit upon opening discover.

**Comment by alsoGAMER** [comment]
Same issue here

**Comment by Joshix-1** [comment]
Doesn't discord now the current voice? The client displays it.

**Comment by trigg** [comment]
This remains an issue until we completely preempt it. 



> Doesn't discord now the current voice? The client displays it.

Unfortunately the API we have access to doesn't share a lot of information you might consider normal, let alone vital. There's no formal way to find out what voice channel a user is in via the streamkit API... at least not one I've found. The other major downside is there is an absolute zero documentation on this API.

I think the best way to fix this bug would be to check the number of guilds before mass-requesting information. If it's above, say, 50 then we request the user choses which servers to watch. Any not selected won't show on voice overlay, but this is probably preferable to this bug.

**Comment by lacksfish** [comment]
Can confirm the "bug" disappears once I left a bunch of unnecessary Discord Servers.

**Comment by Meister1593** [comment]
I think stable version has to be updated to master because after i used it, i instantly got ip banned (i had 50+ servers).

**Comment by Vermoot** [comment]
Same here, used the stable version (installed through `pip`, and got an ip ban and 429 status errors.

**Comment by trigg** [comment]
For anyone feeling brave and a large enough server list (seriously, how does this happen?) could you get the latest git and test by ticking every server and seeing if you get any rate limiting? New connector code MIGHT mean we can no longer trigger rate limit, and I'd be quite happy to have this problem solved.

**Comment by MurdoMaclachlan** [comment]
Been running with 28 servers enabled for the past 20 minutes; not seen any rate limiting yet.

**Comment by trigg** [comment]
We put the warning at 50 servers, but it seems to happen 100+

**Comment by MrMelon54** [comment]
> a large enough server list (seriously, how does this happen?)

I'm in the guilds for games I play and I mostly stay in them for the emotes

**Comment by trigg** [comment]
Sorry, it was meant as a throw away joke, not serious. I'm just about 100 servers away from 100.

**Comment by MrMelon54** [comment]
I just thought I might as well answer it anyway in case you were actually curious

**Comment by ForumPlayer** [comment]
> For anyone feeling brave and a large enough server list (seriously, how does this happen?) could you get the latest git and test by ticking every server and seeing if you get any rate limiting? New connector code MIGHT mean we can no longer trigger rate limit, and I'd be quite happy to have this problem solved.

I'm not sure how many servers I am right now, but i can guarantee that isn't a small list XD
Anyways, I'll test tomorrow (It's 10:08 PM @ UTC-3 now) and I tell y'all here

**Comment by trigg** [comment]
I would very much appreciate that, @ForumPlayer Thank you!

**Comment by trigg** [comment]
I strongly believe this to be fixed as we no longer poll any `GET_CHANNEL`s in bulk. Marking as fixed

**Comment by Victor239** [comment]
If this is fixed can the warning message be removed then?
