### ISSUE TITLE
Text shows [object Object] instead of user name

### ISSUE THREAD

**Issue by allista** [trigg/Discover#135]
![image](https://user-images.githubusercontent.com/6084589/111028091-75251700-8405-11eb-9438-65c42bd33bc1.png)

The `[object Object]` is converted to the user name after _some_ manipulations with the app, e.g. when opening the settings window from the systray.

But the next message also shows `[object Object]`.

**Comment by midget3111** [comment]
Hello, 
Thanks for your report. 
Could of questions... What OS are you running, Which version of Discover Overlay are you running and how did you install it?

Ta!

**Comment by allista** [comment]
- Ubuntu 20.04
- the current master branch cloned today
- installed system-wide via `sudo pip3 install`
- Python 3.8.5

**Comment by allista** [comment]
I can test this in semi-real-time if you need; just point me to the branch where you'll work on the solution, so I can pull and test it.

Tired to figure out the thing myself, but my python is rusty at most, and pyqt is even worse...

**Comment by trigg** [comment]
First a few observations:

- This only affects the logged in user, not other users
- This only affects users who have an unset Nickname
- Discord no longer omits 'nick' and instead sends the string '[object Object]'... not an actual object

Easy enough fix, putting it in now.

**Comment by trigg** [comment]
@allista 

Give the latest git push a try!

**Comment by allista** [comment]
@trigg thanks for the fastest reply and fix! :1st_place_medal: 

I can confirm the fix works:

![image](https://user-images.githubusercontent.com/6084589/111032948-dbb72e80-841f-11eb-94ce-49682bf36833.png)

The issue can be closed.
