### ISSUE TITLE
Problems with 'xdg'

### ISSUE THREAD

**Issue by luni3359** [trigg/Discover#14]
I'm on KDE Neon and xdg isn't included by default. I went over and installed it with ``sudo apt install python3-xdg``, but I'm getting an error:
```
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```
Some commands...
``pip3 freeze | grep xdg``
```
pyxdg==0.26
xdg==4.0.1
```

Here ran python3, imported xdg and then typed ``xdg.`` and double-tapped Tab:
```
xdg.HOME             xdg.Path(            xdg.XDG_CONFIG_HOME  xdg.XDG_RUNTIME_DIR
xdg.List(            xdg.XDG_CACHE_HOME   xdg.XDG_DATA_DIRS    xdg.os
xdg.Optional(        xdg.XDG_CONFIG_DIRS  xdg.XDG_DATA_HOME   
```
Changing line 20 to the following fixes the issues for me.
``from xdg import XDG_CONFIG_HOME as xdg_config_home``

**Comment by trigg** [comment]
Your version of pyxdg is correct but I am not using `xdg==4.0.1`

Best guess without a debian machine about but `xdg` package is incorrect and overrides pyxdg.

**Comment by trigg** [comment]
```
Traceback (most recent call last):
  File "./discover.py", line 21, in <module>
    from xdg import XDG_CONFIG_HOME as xdg_config_home
ImportError: cannot import name 'XDG_CONFIG_HOME' from 'xdg' (/usr/lib/python3.8/site-packages/xdg/__init__.py)
```

For reference, that will break other installations. Need to get to the bottom of this

**Comment by luni3359** [comment]
Yeah I figured it'd break something if you tried it my way, I actually meant to make a PR with a fix but I'm not sure if it's acceptable in python programming to make exception handling right at the importing part...

**Comment by trigg** [comment]
I've done it already for AppIndicator ;)
