### ISSUE TITLE
Enhancement - Horizontal layout for voice overlay

### ISSUE THREAD

**Issue by Antoine-Meloche** [trigg/Discover#144]
It would be nice to have the option of a horizontal voice overlay, so that it can be used at the top of the screen.

**Comment by trigg** [comment]
I'm uncertain how you I'd lay the information out horizontally. Any thoughts on how the information should be displayed ?

**Comment by Antoine-Meloche** [comment]
I don't know if it would be feasible for this option to work with usernames, but I think it would be a very interesting layout for icons only.
