### ISSUE TITLE
Add Twitch chat to overlay!

### ISSUE THREAD

**Issue by sfjuocekr** [trigg/Discover#147]
There is a way to get Twitch chat in the overlay, I used this with the previous discord-overlay versions by just manually changing the ini file and pointing it to this URL:

https://nightdev.com/hosted/obschat/?theme=none&channel=XXX&fade=YYY&bot_activity=true&prevent_clipping=false

XXX = Channel name
YYY = Fade time in seconds, for the messages in chat to fade out.

I would like to see such a "feature" return as I used the previous discord-overlay mainly for that!

**Comment by trigg** [comment]
Currently we don't use any webviews in Discover... I would imagine that's not a simple addition, I'd advise continuing to use discord-overlay for this URL as it shouldn't stop working any time soon.

**Comment by sfjuocekr** [comment]
Since I upgraded to 21.04 I couldn't easily get discord-overlay to work, didn't bother looking into it much further when I saw it was discontinued and recommended to use this repo :)

The chat is just IRC btw, maybe adding a chat overlay would be easier to implement that way?

**Comment by nickistre** [comment]
Looks like this shows how to connect to a Twitch chat in Python: https://www.learndatasci.com/tutorials/how-stream-text-data-twitch-sockets-python/ 

If I ever have some time, I might try to tackle this myself.
