### ISSUE TITLE
KeyError: 'could not find foreign type Surface'

### ISSUE THREAD

**Issue by Starhelper11** [trigg/Discover#148]
I did everything it says yet it doesnt let me it says "Name space Gtk not available" what is needed to be done?

**Comment by Starhelper11** [comment]
Update: now im getting KeyError: 'could not find foreign type Surface'

**Comment by midget3111** [comment]
Hello!
What OS are you trying to install on? which version of Discover?

**Comment by flashrocket** [comment]
Hi,
I too am having the same issue.
OS: Kubuntu 20.04 LTS
`pip3 freeze
apt-xapian-index==0.49
beautifulsoup4==4.8.2
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
discover-overlay==0.3.3
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
evdev==1.3.0
gpg===1.13.1-unknown
html5lib==1.0.1
httplib2==0.14.0
idna==2.8
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lxml==4.5.0
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
pexpect==4.6.0
Pillow==7.0.0
psutil==5.8.0
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
PyQt5==5.14.1
python-apt==2.0.0+ubuntu0.20.4.4
python-debian===0.1.36ubuntu1
python-magic==0.4.16
python-pidfile==3.0.0
pyusb==1.1.1
pyxdg==0.27
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.16.0
sip==4.19.21
six==1.14.0
soupsieve==1.9.5
systemd-python==234
sysv-ipc==1.0.0
ubuntu-advantage-tools==27.0
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
webencodings==0.5.1
websocket-client==1.0.1
xkit==0.0.0
`

**Comment by trigg** [comment]
Looks similar to https://github.com/Cimbali/pympress/issues/7
