### ISSUE TITLE
Support for transparent user icons

### ISSUE THREAD

**Issue by yaomtc** [trigg/Discover#150]
I have a transparent avatar on Discord. It shows up with a black background. Is it possible to fix this?

**Comment by trigg** [comment]
This will take a bit to work out. Currently overlay user icon is given in JPG without transparency 
`discover_overlay/voice_overlay.py:360`

**Comment by yaomtc** [comment]
So it that the Streamkit API only provides JPEG? 

I don't know if this comment is still relevant, but: https://github.com/wohali/oauth2-discord-new/issues/14#issuecomment-432332004

**Comment by trigg** [comment]
I've changed the user source, it appears to have not broken anything but whether it fixes this is another question. I'll test once I'm done compiling kernels

**Comment by trigg** [comment]
tested and works

**Comment by yaomtc** [comment]
Just rebuilt it, looks great. Thanks for the update!
