### ISSUE TITLE
How to remove the avatar edges?

### ISSUE THREAD

**Issue by pofdzm** [trigg/Discover#152]
![image](https://user-images.githubusercontent.com/63299895/123133749-bb543280-d458-11eb-8832-b2fc6d569231.png)
As you can see, there is that pixelized black edges that looks a bit ugly. How to remove them?

**Comment by midget3111** [comment]
Hello! Which version of Discover are you running, and on which distribution?

**Comment by trigg** [comment]
Just eyeballing the picture I'd guess for one reason or another compositing is not being used. What window manager and composite manager are you using? Have you selected 'Force XShape' in settings?

**Comment by pofdzm** [comment]
>Have you selected 'Force XShape' in settings?

No, I did not. 

I use Openbox as WM, also I am not sure what compositing or composite manager means.

**Comment by pofdzm** [comment]
> Hello! Which version of Discover are you running, and on which distribution?

I use the latest probably, I installed it like 5-6 hours ago. It is elementary OS 5.1.7 Hera (based on Ubuntu 18.04).

**Comment by trigg** [comment]
Ah, well this fully explains that. A composite manager is something that works along side window managers to allow semi-transparent windows. For a debian based I believe 'compton' is the way forward.

Man page: https://manpages.debian.org/unstable/compton/compton.1.en.html

**Comment by pofdzm** [comment]
I will close the issue for now cause the app literally stopped working for no reason, so I cant confirm if this is solved or not.
