### ISSUE TITLE
Hide overlay after leaving the voice channel

### ISSUE THREAD

**Issue by pervoj** [trigg/Discover#155]
When I leave the voice channel, the overlay will stay visible. It would be nice when the overlay will hide after leaving.

**Comment by midget3111** [comment]
Hello,
Thanks for the report. 
Could I ask where you installed discover from and which Distribution you're running it on?

Many thanks.

**Comment by pervoj** [comment]
I installed Discover using `pip install discover-overlay`. OS: Fedora 34 and GNOME 40

**Comment by midget3111** [comment]
Okay, would you be able to try the latest testing to see if the issue persists? 

This may well already be fixed and we just need to push a new stable build.

**Comment by pervoj** [comment]
Same issue when installing from `master` branch

**Comment by midget3111** [comment]
Okay, ta! 

Anything in the command line when it happens?

I suspect it's something to do with Gnome 40, but I'll ask @trigg to take a look into it when he gets time.

**Comment by pervoj** [comment]
Only when connecting to the channel: `INFO:root:Joined room: General` but there is no output after leaving.

**Comment by trigg** [comment]
How are you leaving room? 

For me when pressing the hang up button the voice overlay will disappear but text overlay will remain.

**Comment by pervoj** [comment]
https://user-images.githubusercontent.com/71781857/126977686-313d150b-d932-4049-9d25-151bd0d4191c.mp4
