### ISSUE TITLE
doesn't display speaking status updates (sometimes)

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#157]
it stopped working for me.
I tried the latest two commits. Both list a bunch of channels until there comes "WARNING:root:Getting 270 rooms" after that nothing happens. 
The icon in the sys tray is present.
The voice channel I'm in and the text channel I specified get both printed.

**Comment by trigg** [comment]
No apparent error here. What isn't working?

**Comment by Joshix-1** [comment]
sorry. After restarting discord it works now.

**Comment by Joshix-1** [comment]
I don't know why, but it sometimes doesn't work.

**Comment by Joshix-1** [comment]
I get the SPEAKING_START and SPEAKING_STOP events from discord, but nothing gets displayed.

**Comment by trigg** [comment]
Does the run order of Discord/Discover decide if this happens?

**Comment by Joshix-1** [comment]
Discover crashes sometimes if it runs when discord doesn't run.
It only registers SPEAKING_START and SPEAKING_STOP when I start it when I'm in a channel. But when I then switch channels it doesn't register it. But it always registers me speaking in the channel I  was when I started it.

**Comment by Joshix-1** [comment]
It seems like discover doesn't register me joining a channel.

**Comment by trigg** [comment]
Looking into this, an assumption in discord_connector.py means we're never calling `on_connected` if the user has chosen a subset of guilds in the new changes. I'll look into this while I'm here.

**Comment by Joshix-1** [comment]
the current commit seems to work.
