### ISSUE TITLE
Rename close to something more common

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [trigg/Discover#16]
Hey. One thing that stood out to me a bit (with this as well as [DiscordOverlayLinux](https://github.com/trigg/DiscordOverlayLinux.git)) is that there is a button labelled "close" whilst I'm used to it being labelled "Quit" or "Exit" instead. I feel that "close" is more related to partial terminations (closing a window) whilst "quit" and "exit" more clearly communicate that any related processes will be terminated.

I recommend looking at some application tray icons and surveying what they are labelled to come to your own conclusions. Here are mine:

<details>

**Close: &nbsp;&nbsp;0
Exit: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4
Quit: &nbsp;&nbsp;&nbsp;11**

Software observed:
* OBS
* Steam
* Itch.io
* Discord
* Zoom
* Pidgin
* Slack
* Jami
* Telegram
* Skype
* Korganizer
* Joplin
* Nextcloud
* gnome-pie
* easystroke
</details>

**Comment by i-need-to-tell-you-something** [comment]
I would have submitted a PR for that myself, but then I wasn't sure if I may also rename all the variables and function/method names from "close" to "quit" as well or would that be too much. I think it would improve code quality and safety if user-facing parts and code are more similar.

**Comment by trigg** [comment]
I'm uncertain how I feel about this, will see what opinions are

**Comment by i-need-to-tell-you-something** [comment]
@trigg Did you disagree with the pattern I observed? Does a significant fraction of the software that you use have "close" instead of "exit" or "quit"?
