### ISSUE TITLE
Change input type for guild allow list

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#161]
A text box with comma separated values may not best convey the use of this feature.

I think we should cache known guild id's and names and have a list of tickboxes

**Comment by Joshix-1** [comment]
known guild id's and names are already cached. The code checks if the guild_id is cached before trying to request the guild as otherwise it would try to request while typing. 
And I agree a list of tickboxes would be better. (I just don't really know gtk)

**Comment by trigg** [comment]
> already cached

Cool. Suspected so but for the sake of my own memory I try to be verbose.

> I just don't really know gtk

Yeah, I can't fault you there. It's not a drop-in replacement but I plan to do this today

**Comment by Joshix-1** [comment]
You should probabl move the setting to the general settings tab, as I think it affects the text part too.

**Comment by trigg** [comment]
Completed in latest, only partially tested
