### ISSUE TITLE
Not connecting to Discord

### ISSUE THREAD

**Issue by gjkf** [trigg/Discover#17]
Cloned and installed the tool. As soon as I run `discover-overlay` nothing appears on screen, the tray icon is a grey circle that allows me to change the settings but on the terminal I see the following
```
/usr/local/bin/discover-overlay:1000: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
Could not find monitor : None
Could not find monitor : None
```
On Ubuntu 18.04.

**Comment by trigg** [comment]
No error here. Are you in a voice channel?

**Comment by gjkf** [comment]
Yes, I was. I also tried to leave and rejoin and close and reopen both Discord and Discover. What should be the correct order of operations?

**Comment by trigg** [comment]
There isn't a correct order. 

Have Discord open
Have Discover overlay running

To force a re-draw you can mute/unmute yourself. Also double check your settings so you know where you're looking for the overlay.

More log might be interesting as the snippet you've given doesn't indicate it has managed to connect to the client

**Comment by gjkf** [comment]
![image](https://user-images.githubusercontent.com/8215189/94347572-baab7e80-0035-11eb-9409-fe11a01393c4.png)

Above you can see a screenshot of what I see. You can see both Discord and Discover running. I am in a voice chat (I tried both in a voice chat alone where I still assume I would see myself and in another one).

I muted and umuted myself a few times, with no luck.

On the console that is all I am getting, if you tell me where to look I can provide you with more logs.

**Comment by trigg** [comment]
So the lack of 'Connected' message means it's not managing to connect to discord. How have you installed discord?

**Comment by gjkf** [comment]
Of course I have, you can see it running on the left (second icon from the bottom) and on the bottom. Should I give Discover any kind of key to let it connect?

**Comment by midget3111** [comment]
> So the lack of 'Connected' message means it's not managing to connect to discord. How have you installed discord?

I'm going to assume snap or flatpak?

**Comment by gjkf** [comment]
If I am not mistaken, I have installed Discord via the .deb file that can be found on their website. If needed I can uninstall it and just reinstall it from there.

**Comment by trigg** [comment]
Latest push should make it clear when no connection has been established

**Comment by gjkf** [comment]
Exactly, just updated and the message `Unable to connect to Discord client` pops up on the console.

**Comment by trigg** [comment]
Just to cover our bases

`sudo snap remove discord`

**Comment by gjkf** [comment]
`snap discord is not installed`

**Comment by trigg** [comment]
So it's absolutely not that, good to cross it off the list. Next up is to work out what's stopping a connection then

**Comment by gjkf** [comment]
Looking online I discovered the [wsdump.py](https://github.com/websocket-client/websocket-client#wsdumppy) tool and tried to run it using the link found on line 1034 (appending the auth_token at the begining of the file). This was the output:
```
cossu@cossu-TUXEDO:~$ ws://127.0.0.1:6463/?v=1&client_id= (auth_token)
[1] 8754
cossu@cossu-TUXEDO:~$ bash: ws://127.0.0.1:6463/?v=1: No such file or directory
``

**Comment by trigg** [comment]
After installing websocket-client you'd have a copy of that in `~/.local/bin/wsdump.py` which is the one for the version you're running

**Comment by trigg** [comment]
This aside, in a broswer put that URL but switch ws for http. It should come up with a "Not found" message if you're able to connect

**Comment by gjkf** [comment]
For some reason, now it works.

The difference was that instead of running
`python3 -m pip install websocket_client`
as you have in your `README.md`, I ran
`pip3 install websocket_client`
and relaunched `discover-overlay`.
Seems to be working since it immediately popped up an authorization window of Discord.

**Comment by trigg** [comment]
Good news! So we'll go with magic since those two are meant to be synonymous.
