### ISSUE TITLE
Can't exclude from blur on picom

### ISSUE THREAD

**Issue by santarl** [trigg/Discover#170]
Cannot exclude discover-overlay from blur picom as mentioned on ibhagwan/picom#36

tried getting class_g from xprop as mentioned in [this comment](https://github.com/ibhagwan/picom/issues/36#issuecomment-925378300) with this command: `xwininfo -root -tree | grep discover`

for which I got 

```
0x2e00007 "Discover Text": ("discover-overlay" "Discover-overlay")  50x50+0+0  +0+0
     0x2e00003 "Discover Voice": ("discover-overlay" "Discover-overlay")  1920x1080+0+0  +0+0
     0x2e00001 "discover-overlay": ("discover-overlay" "")  10x10+10+10  +10+10
        0x2e0000f "discover-overlay": ("discover_overlay" "discover_overlay")  16x16+12+12  +1808+12
        0x2c0000f "xwininfo -root -tree | grep discover /home/jay": ("kitty" "kitty")  1882x493+2+2  +19+568
     0x3a0017b "discover_overlay.desktop": ("Firefox" "firefox")  268x54+312+813  +312+813
```
I've tried adding them to exclude list in picom config and that doesn't seem to change anything. ie: discover-overlay still ends up blurring the entire screen when opened.

Here is how the relevant part from my picom config looks:

```
# Exclude conditions for background blur.
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'URxvt'",
  "class_g = 'discover-overlay'",
  "class_g = 'Discover-overlay'",
  "class_g = 'discover_overlay'",
  "class_g = 'Discover_overlay'",
  #
  # prevents picom from blurring the background
  # when taking selection screenshot with `main`
  # https://github.com/naelstrof/maim/issues/130
  "class_g = 'slop'",
  "_GTK_FRAME_EXTENTS@:c"
];
```
and here is an screenshot of how it looks when I open discover-overlay when picom is active

![2021-10-15_00-01](https://user-images.githubusercontent.com/74417622/137375695-5bbed661-9aa0-4444-bd18-b92b52f45721.png)

is the class_name something other than "discover-overlay" or am I missing something here?

thanks

**Comment by trigg** [comment]
Interestingly, attempting to reproduce this I get a completely unrelated problem right away. In the mean time could you try adding the two options below and let me know if that helps?

```
blur-background-exclude = [
  "name = 'Discover Text'",
  "name = 'Discover Voice'"
];
```
