### ISSUE TITLE
Monitor freeze after starting programm

### ISSUE THREAD

**Issue by fugohan** [trigg/Discover#173]
**Steps to Reproduce**
1. Open Programm and then second (main) monitor freezes.

**Expected behavior**
Program should start and display the overlay. 

**Problematic behavior**
Monitor freeze and I can't drag any windows from that monitor. 

**Desktop (please complete the following information):**
Ubuntu 20.04

**Installation Method**
 - Not sure if I'm using stable or testing cause I installed both
 - conda doesn't work for me but if I use the setup.py with /usr/bin/python3.8 i can setup it

Terminal Output: 

INFO:root:Falling back to Systray : Namespace AppIndicator3 not available
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None

**Comment by fugohan** [comment]
I'm pretty sure that I'm using gnome but how can I find out if I'm using X11 or Wayland?

**Comment by trigg** [comment]
Sounds like an XInputShape issue, but shouldn't happen in X11. Uninstall the stable, update the latest and test with that
