### ISSUE TITLE
Discover freeze after this Indexerror

### ISSUE THREAD

**Issue by fugohan** [trigg/Discover#178]
I got this output from my terminal. Discover didn't crashed, but if I mute myself there is no change. 

```File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discord_connector.py", line 638, in do_read
  self.on_message(msg)
File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discord_connector.py", line 383, in on_message
  self.request_text_rooms_response[j['data']
IndexError: list assignment index out of range
```

I'm using gnome with x11.

**Comment by MurdoMaclachlan** [comment]
It looks like this happens when enough new channels are created after the overlay started that the requested channel's position has been pushed higher than the length of channels Discover expects. My test process was:

- Select last channel in the list
- Create new channel before it (Discover doesn't know this channel exists since channels are cached)
- Select some other channel
- Select what Discover thinks is the last channel again; Discord tells Discover its position is X, but because of the new channel, X is outside the range Discover expects and it crashes

My print() statements weren't very informative, but here's the log output of my testing with explanatory notes.

![image](https://user-images.githubusercontent.com/47920497/158206552-86175688-b0bc-41db-a252-2991c167b291.png)

I imagine the way to fix this would just be to catch the error and request the details for that guild again, but I'm not familiar with Discord's API at all, so even with some poking around I wasn't sure how to do it.

**Comment by trigg** [comment]
That's one heck of a good catch. I don't tend to see any changes in channels or guilds so that would've never occurred to me. 

I'll look at this shortly, thanks!

**Comment by MurdoMaclachlan** [comment]
Hm, not sure how the caching works but something here doesn't seem to be updating properly? It goes into the if & gets the rooms again, but none of the data seems to have changed after the fact.

![image](https://user-images.githubusercontent.com/47920497/158225221-e208e1d2-198d-4f57-866f-adfcc7df9b2b.png)

**Comment by MurdoMaclachlan** [comment]
Well that doesn't seem right (it's this regardless of what server I have selected)

![image](https://user-images.githubusercontent.com/47920497/158226816-577f4fdf-4cab-4ff1-8f96-ca22d5c9635b.png)

**Comment by trigg** [comment]
My apologies, care to try once more? Didn't actually stop it crashing, did I?

**Comment by MurdoMaclachlan** [comment]
Oop, Discord thinks I've been creating/deleting too many channels apparently :P 

I'll get back to you when my ratelimit expires 😆

**Comment by MurdoMaclachlan** [comment]
Yeah, it seems to get stuck in a loop even after it re-requests, so that would explain the ratelimit

![image](https://user-images.githubusercontent.com/47920497/158241101-d70f2173-90b9-4471-9fd8-c008a5830e3f.png)

**Comment by midget3111** [comment]
Is this issue still occurring @MurdoMaclachlan ?

**Comment by MurdoMaclachlan** [comment]
As of 0.5, yep. It doesn't crash any more, but the channel list doesn't seem to actually refresh, so you just lose the ability to look at channels that pushed out of range.

**Comment by trigg** [comment]
the replied 'position' from the API has no bearing on reality, from what I can see.
I've stopped using it and gone back to unordered channels.

Hopefully this will fix it

**Comment by MurdoMaclachlan** [comment]
IndexError issue seems to be fixed, but there's still a problem going on. Doing the steps to reproduce the old issue, I can switch back to the channel that previously would've been pushed out of bounds without a problem.

But, after a new channel has been created, attempting to open the settings window generates the following error:
![image](https://user-images.githubusercontent.com/47920497/162485186-3bf5408c-3eb7-4243-8bbf-a5ff3269b9b6.png)
Discover still receives updates if I send messages to the selected channel, but it means that if a new channel gets created while the settings window is closed I can't access the settings again until I restart the program.

It also looks like the channel list doesn't actually get updated to include the new channel except on restart (either that or I couldn't work out how to get it to refresh :P). I'm not sure if that's tied in or not but it might be worth adding a periodic refresh or a button to force it or something.

**Comment by trigg** [comment]
I... wow how did I manage to write a bug that's that stupid and not find it?

I accidentally set a function to None.

**Comment by trigg** [comment]
Ok, that new one should be corrected. Let me know if this updates as it should now

**Comment by MurdoMaclachlan** [comment]
It's usually the 'obvious' ones that slip past in my experience. 😆 

No crashing occurring with the most recent commit. That channel list still doesn't refresh to include the new channel, but I'm not sure if that's something for a different issue or not.

**Comment by trigg** [comment]
Does it correct if you switch off to another server and back? 

I don't believe we want to frequently poll all servers and unless a major api change has happened, there's no notification of new rooms

**Comment by trigg** [comment]
Might simply need a 'refresh list' button to the right?

**Comment by MurdoMaclachlan** [comment]
Well, interesting note on that: I tried to change server, but the channel list doesn't change. Both servers *are* enabled in the config, *and* Discover knows I'm in the VC for the second server. Doesn't seem to be able to get the text channels for it, though, even when I start the program with it selected. I think that was working before. 🤔

Though a 'refresh list' button sounds like it would do the trick for getting new channels, at least. 😅

**Comment by trigg** [comment]
Added refresh to latest git and made lists go insensitive while updating.

**Comment by MurdoMaclachlan** [comment]
Hmm, had some 'interesting' experiences with this:

- The refresh button on one of my two enabled servers doesn't seem to do anything; it clicks and the list briefly greys out, but the new channels don't show up without a restart.
- I had a strange time getting the other server to work. For a while it would sometimes show selectable channels and sometimes not (and some of the channels would show up in the list three or four times). Fiddling with the refresh button and changing between servers seems to have got its channels cached properly now, without duplications.
- One time I tried to refresh a server I did't have enabled in `config.ini` and the program got stuck in an eternal loop of re-requesting, even when I restarted it. I fixed it by manually blanking the `channel` and `guild` fields in the config file, and now I can't reproduce it.

**Comment by trigg** [comment]
Sorry I didn't reply sooner. I've done a rather large overhaul of the connector which, if not fixing this, has at least changed all the relevant code.

**Comment by MurdoMaclachlan** [comment]
No worries! Working perfectly on my end so far. :D

**Comment by trigg** [comment]
This is good news! I'd been rather hoping to squash a few issues all at once
