### ISSUE TITLE
Settings windows does not fit on screen and can't be resized when in large number of servers. 

### ISSUE THREAD

**Issue by forever-and-a-day** [trigg/Discover#180]
**Steps to Reproduce**
1. Be in a large number of servers (in my case ~80)
2. Start Discover
3. Dismiss the large server number warning
4. Right click on the tray icon and choose "Settings"
5. Settings window top is above the top of the screen, and bottom is below the taskbar/panel and screen (even when auto hiding is on)

**Expected behavior**
The "Search Servers for User" list is smaller (unsure if actual solution), allows the window to be resized, and can be fully used by either scrolling through servers or using the filter box above it. 

**Problematic behavior**
The Setting window's title bar and window controls are above the screen, so it can't be moved or closed with the mouse. The bottom of the window extends beyond Cinnamon's default panel/taskbar, so  a server in "Search Servers for User" can't be selected without using the "filter" box above the list.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon x86_64
(Linux Kernel: 5.11.0-37-generic)

**Installation Method**
 - pip

**Additional context**
Screenshot:
![windowsizebug](https://user-images.githubusercontent.com/10383240/138986495-ab07230e-6f9a-4727-b697-d788680a7aed.png)

**Comment by trigg** [comment]
I'm marking this as solved currently as the scroll box appears to be working now. Open it again if this crops up or you're trying this on a much lower resolution than I have tested on.
