### ISSUE TITLE
No longer launches

### ISSUE THREAD

**Issue by yaomtc** [trigg/Discover#181]
Discover no longer works for me, and I'm not sure why. I've tried uninstalling and reinstalling, I've tried recompiling, tried switching to -git version, no dice. See terminal output below.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Installation Method**
 - AUR (discover-overlay)

**Additional context**
Terminal output: https://gist.github.com/yaomtc/7b28723a6ce45ec5aa75a68b31abfb52

I am using Plasma on Xorg, all packages are up to date.

**Comment by Taragolis** [comment]
@yaomtc seems like your configuration corrupted

try to delete `~/.config/discover_overlay/config.ini` or move somewhere:
```shell
mv ~/.config/discover_overlay/config.ini ~/.config/discover_overlay/config.ini.orig
```

**Comment by yaomtc** [comment]
That fixed it, thanks!
