### ISSUE TITLE
Settings windows are Ugly.

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#187]
We need to plan a better layout and to move related options together

**Comment by trigg** [comment]
![Screenshot_2022-01-15_16-56-03](https://user-images.githubusercontent.com/535772/149630508-a14aeeda-0a1b-4301-b5d5-a44d5dc80ebf.png)
Now I wouldn't call this pretty but I believe it's an improvement. Opinions, thoughts?

**Comment by midget3111** [comment]
Left looks good. Right column needs better spacing

**Comment by trigg** [comment]
![Screenshot_2022-01-15_17-03-21](https://user-images.githubusercontent.com/535772/149630704-bae9ed06-3bcf-4f70-b638-40f5a9619376.png)

?

**Comment by trigg** [comment]
![Screenshot_2022-01-15_17-05-35](https://user-images.githubusercontent.com/535772/149630753-733cd08a-2ecb-4674-80e7-c78f3e27e589.png)

**Comment by trigg** [comment]
I'm calling this good enough. Re-open when I make a mess of it next time
