### ISSUE TITLE
Overlay position is wrong

### ISSUE THREAD

**Issue by guppy42** [trigg/Discover#188]
**Steps to Reproduce**
1. Open settings
2. Select "Anchor to edge"
3. For overlay location choose anything other than Left, Top
4. Overlay is placed at rough 2x the intended X,Y position

**Expected behavior**
The overlay to appear where you selected

**Problematic behavior**
The overlay appears in the wrong place:

![Position_fail](https://user-images.githubusercontent.com/6497829/149523328-8dbfa5f5-11ad-40f5-9838-7888a5006c9a.jpg)

This also affects the the 'floating window' if you move it from 0,0 it will double it's current x,y coordinates ( floating_x, floating_y in the config file ) every time you save causing it fly off screen if you position it outside the upper left quadrant of the screen.

it's exactly double as well in both coordinates - at first I suspected it was related to having two screens, but with the position being exactly off by x2 I'm starting to suspect Discover handles Hi-DPI wrong 

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 (Cinnamon)
 - Two monitors:
 - DP-0 : 3840 x 2160, user interface scale : double (Hi-DPI) 
 - DP-4 : 2560 x 1600, user interface scale : double (Hi-DPI) 

**Installation Method**
 - sudo apt install python3-pip
-  python3 -m pip install discover-overlay

**Comment by midget3111** [comment]
Thanks for the report. We'll look into this and hopefully get it sorted!
