### ISSUE TITLE
Be able to toggle the overlay with keyboard shortcuts

### ISSUE THREAD

**Issue by ErikReider** [trigg/Discover#190]
It would be cool if I could toggle the overlay when in game or when on the desktop with a simple keyboard shortcut.

The traditional way of doing so on X11 shouldn't work on Wayland clients (please correct me if I'm wrong) so what I did for [swaync](https://github.com/ErikReider/SwayNotificationCenter) is that I created a client and a server. The server creates a DBus server (or whatever the correct term would be) with a method for toggling while the client calls sed method when invoked by a shortcut in my [Sway config](https://github.com/ErikReider/Linux/blob/e492fddc58a10c5febdaea844e5cecbab78decdd/dotfiles/swayConfig/sway/sway.d/08_hotkeys.conf#L47)

**Comment by trigg** [comment]
I'm a bit loathe to add the complexity of DBus when we're already dealing with RPC with extra CLI calls.

Most likely add '--hide' and '--show' RPC options which in my experience will work from any desktop environment
