### ISSUE TITLE
[Feature request] Add a default avatar for user withouth a avatar one 

### ISSUE THREAD

**Issue by Moonl1ghter** [trigg/Discover#191]
First, this software is great and works fantastic!

When a user has not set a avatar, only their name shows up. It would be nice to have a default avatar to replace it, just like Discord does with their own overlay. I suspect it can not be the Discord icon, because that might be copyrighted, but users could specify their own or we could have Tux :).

Keep in mind, this is not important, but nice to have.

**Comment by trigg** [comment]
Ah #8 shows up again.

**Comment by Moonl1ghter** [comment]
This issue is still present for me, will see if I can provide some more feedback/logs.

**Comment by trigg** [comment]
You'll need to `git pull` the latest commits, if you haven't already. How are you installing ?

**Comment by Moonl1ghter** [comment]
I'm using the discover-overlay-git package from the AUR, so should have the latest commits.
