### ISSUE TITLE
Unable to select text channel for text overlay

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#192]
**Steps to Reproduce**
1. Launch overlay
2. go to settings
3. select text tab
4. server is selected
5. channel is greyed out

**Expected behavior**
able to choose which channel to display text from

**Problematic behavior**
yes.

**Desktop (please complete the following information):**
Arch

**Installation Method**
 - AUR

**Additional context**
I need sleep

**Comment by trigg** [comment]
temporary work around, change font size. I'm uncertain why the list doesn't populate but should be fixable soon

**Comment by midget3111** [comment]
Ta
