### ISSUE TITLE
No transparent background with Picom with fullscreen app enabled

### ISSUE THREAD

**Issue by jarrard** [trigg/Discover#199]
Just a small bug report here. It seems this doesn't work too well with Picom and fullscreen apps (which enables unredirection) as the background goes black for discover, you can minimize this issue by placing the window position and resizing it.

Not sure if this can be fixed?

**Comment by trigg** [comment]
What settings are you using to run Picom?

Last I knew unredirect mode would decide to only draw the top window - in this case only the overlay

**Comment by trigg** [comment]
It would be worth testing it again with Force XShape turned on ( Settings -> Core -> Force Xshape)

**Comment by jarrard** [comment]
picom -b --experimental-backends --config ~/.config/picom.conf

Config is just the example config provided. I enabled vsync and redirect mode for better game/fullscreen performance. 

Am using it under Plasma atm but was under XFCE. I don't like Kwin as it gives me allot of frame skipping on my setup.

**Comment by trigg** [comment]
As with #80 then.

'Unredirect window' means the compositor effectively disables itself and only displays one window. It's automatically at odds with drawing a window over top of your current fullscreen window.

**Comment by jarrard** [comment]
Bummer. Xshape just draws the large box either way.

**Comment by trigg** [comment]
In the case of Picom and unredirect ... Picom simply isn't drawing anything after the most top-level window.

**Comment by jarrard** [comment]
Well it draws just fine, its just the background is not transparent and thus black box. Assuming you use the place position method and not the fullscreen align one which just ends up drawing a black box over your fullscreen app.

**Comment by trigg** [comment]
The black box & background are being drawn by picom. Try running picom without unredirect

**Comment by jarrard** [comment]
I'll give it a go.

**Comment by trigg** [comment]
As with #170 you'll need to exclude shadows (similar method as exclude blur) from being drawn on the overlay window.

Drawing icons aligned to the opposite end of text would need more than an option, the implementation would be non-trivial.

**Comment by jarrard** [comment]
> Drawing icons aligned to the opposite end of text would need more than an option, the implementation would be non-trivial.

You could also allow unlimited padding number instead of limiting it to 1000, then you can align to left of screen and push to 3000 to right of screen and keep the icons on the left alignment.

**Comment by trigg** [comment]
I'm aware of the way Mango hud and mumble overlay function, but I'm not interested in rewriting the whole project to work that way. I believe it's the wrong way to do it as then it only works in opengl and vulkan games.

**Comment by jarrard** [comment]
Yes; I thought it might just be handy as a toggle option. I'd only assume most people would use discord overlay in-games anyway.

But obviously if its way too much work. Perhaps a workaround will be realized down the line for this unredirect issue.

**Comment by trigg** [comment]
We'd need to start from scratch in C, C++ or maybe Rust. Won't fix until total rewrite

**Comment by jarrard** [comment]
I might have found a way to resolve some of the issue.  Possibly with shadow-exclude option in picom, however I do not know the class element name of the floating window or its fullscreen overlay option.  'discover-overlay'  is not it apparently.
