### ISSUE TITLE
[wayland/KDE Plasma] Edit readme to include KDE wayland dependency gtk-layer-shell

### ISSUE THREAD

**Issue by TobiPeterG** [trigg/Discover#204]
**Steps to Reproduce**
1. install discover-overlay
2. try to launch it
3. See error

**Expected behavior**
no errors

**Problematic behavior**
errors

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Installation Method**
 - AUR

**Additional context**
I get the following error message:
Traceback (most recent call last):
  File "/usr/bin/discover-overlay", line 33, in <module>
    sys.exit(load_entry_point('discover-overlay==0.4.1', 'console_scripts', 'discover-overlay')())
  File "/usr/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 227, in entrypoint
    Discover(rpc_file, line)
  File "/usr/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 45, in __init__
    self.create_gui()
  File "/usr/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 120, in create_gui
    self.voice_overlay = VoiceOverlayWindow(self)
  File "/usr/lib/python3.10/site-packages/discover_overlay/voice_overlay.py", line 31, in __init__
    OverlayWindow.__init__(self, discover)
  File "/usr/lib/python3.10/site-packages/discover_overlay/overlay.py", line 90, in __init__
    self.set_wayland_state()
  File "/usr/lib/python3.10/site-packages/discover_overlay/overlay.py", line 123, in set_wayland_state
    if not GtkLayerShell.is_supported():
NameError: name 'GtkLayerShell' is not defined

I'm using KDE Plasma with wayland, might this be the issue?

**Comment by midget3111** [comment]
Unfortunately Wayland on KDE doesn't support any kind of shell making API as far as I know. We currently only support wlroots based Wayland.

**Comment by TobiPeterG** [comment]
> Unfortunately Wayland on KDE doesn't support any kind of shell making API as far as I know. We currently only support wlroots based Wayland.

Oh, OK, thank you very much!
Should I still keep the issue open or close it?

**Comment by midget3111** [comment]
Leave it open for now. I imagine we'll have to look into implementing this in the future if they get around to adding the means!

**Comment by ThaSiouL** [comment]
Have you tried installing community/gtk-layer-shell? the overlay has worked flawlessly for me on kde wayland for the last 4 months... 

>ou might just need to switch to x11 for initial setup since the settings windows freezes as soon as I try to interact with it in KDE Wayland since it got refreshed.

**Comment by trigg** [comment]
This is good news then! I must have missed that in updates. That leaves only Gnome and Weston to play catch up.

**Comment by TobiPeterG** [comment]
> Have you tried installing community/gtk-layer-shell? the overlay has worked flawlessly for me on kde wayland for the last 4 months...
> 
> > ou might just need to switch to x11 for initial setup since the settings windows freezes as soon as I try to interact with it in KDE Wayland since it got refreshed.

I just installed it, with gtk-layer-shell, it works flawlessly! :)
Thank you very much!

**Comment by midget3111** [comment]
> > Have you tried installing community/gtk-layer-shell? the overlay has worked flawlessly for me on kde wayland for the last 4 months...
> > > ou might just need to switch to x11 for initial setup since the settings windows freezes as soon as I try to interact with it in KDE Wayland since it got refreshed.
> 
> I just installed it, with gtk-layer-shell, it works flawlessly! :) Thank you very much!
> 
> This should probably be mentioned in the readme somewhere

It is under the Arch Wayland dependencies section. We'll add a separate note about needing it for KDE Wayland. Ta!

**Comment by trigg** [comment]
I'm going to close this for now, KDE snuck layer-shell support in while I wasn't looking. Good on them!

Update to docs is in order but the initial issue is resolved
