### ISSUE TITLE
Gamescope integration and multiple outputs

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#205]
Gamescope only allows one external overlay window. 

Our system of separating text & voice overlays into two windows finally backfired!

For now I've hard disabled text overlay while in gamescope mode but this is far less than ideal. Proposed change is to merge both windows into one large window and simply render in correct locations. 

Be sure to alert picom bug tracker to the change in window titles!

**Comment by midget3111** [comment]
Might also be worth talking to Goverlay & gamescope projects

**Comment by trigg** [comment]
With some testing have proben having both voice overlay and mangahud overlay results in mangohud showing and voice only reappearing when mangohud is set to off.

This is acceptable, in my opinion, and only leaves us with trying to draw text overlay into voice overlay.

**Comment by trigg** [comment]
Piggybacking is sorted in latest. Auto-opt in for gamescope env
