### ISSUE TITLE
Unclean close of overlay when running on Gamescope & Steam when installed via flatpak

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#206]
**Steps to Reproduce**
On Deck or any system with a Gamescope & Steam in game pad ui, with both Discord and Discover-Overlay installed via flatpak launch both these apps and attempt to close the overlay or Discord.

**Expected behavior**
Choosing 'Close overlay' or 'Exit game...' should cleanly close the overlay app

**Problematic behavior**
Steam returns to a spinning circle as if it's expecting the app to start up again, In library the game launch button shows as 'Resume' not 'Run'.

**Desktop (please complete the following information):**
Gamescope & Steam session on Deck

**Installation Method**
Flatpak

**Additional context**
This is very likely to do with both Non-Steam games having their binary as "/usr/bin/flatpak" Attempt again with direct app location.

Work around is to press 'Steam' and choose 'Power' and then 'Restart Steam Client' to close both and return to a clean state.

**Comment by trigg** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/8474

Pushed it upstream as at this rate I've proven it's not flatpak or overlay specific.

**Comment by midget3111** [comment]
If it's not Discover specific, can this be closed?

**Comment by trigg** [comment]
I'd argue keep it here to avoid getting new issues for this by new Deck users.

**Comment by trigg** [comment]
This has been fixed in latest Steam Beta. Amazing!
