### ISSUE TITLE
Feature request: Normalised audio

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#213]
Might be outside of the remit of this project. 

But, it might be nice to have a normalised audio option in core settings. Specifically targeting steamdeck as we know it's using pipewire and not likely to change from that.  

Normalised audio would mean all system volume would prioritise Discord over games & individual users would all be the same volume. Unsure whether this last bit is possible. Assume this is probably not going to happen.

**Comment by trigg** [comment]
Deck has an pile of audio processing already, this is way beyond this project
