### ISSUE TITLE
Settings window "unresponsive" on KDE Wayland

### ISSUE THREAD

**Issue by ThaSiouL** [trigg/Discover#216]
**Steps to Reproduce**
- Open Settings window from Tray Icon on KDE Wayland

**Problematic behavior**
The window turns grey and gets a "(Not Responding)"  in the title as long as it is in focus. Everything is still usable but it is quite annoying when selecting colors. Overlay also continues working without any problems.

**Desktop (please complete the following information):**
 - OS: Arch (Endoeavor OS) DE: KDE Wayland

**Installation Method**
 - AUR

**Additional context**
When started from shell, the following Error is logged as soon as the window is opened:

`(discover-overlay:36029): Gdk-CRITICAL **: 16:45:31.808: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
`

**Comment by trigg** [comment]
I've been unable to replicate this error. Fresh Endeavour OS install, KDE, installed by AUR.

**Comment by ThaSiouL** [comment]
hmm strange. I tried deleting the settings and switching to the AUR Git Package, but same result. 

Maybe i have a certain GTK package missing or something. I have some weird problems sometimes on wayland because of my nvidia graphics, but i don't think that is likely in this case.

I also have the following error messages when starting the app, but they are probably unrelated.

`** (discover-overlay:23223): WARNING **: 13:20:05.384: gtk-layer-shell v0.7.0 may not work on GTK v3.24.33. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
ERROR:root:Unable to load file share/icons//hicolor/256x256/apps/discover-overlay-default.png
`

**Comment by midget3111** [comment]
Very odd. If you're installing from the AUR it should grab the necessary packages, Have you tried direct install via pip, or seeing if the Flatpak works?

**Comment by ThaSiouL** [comment]
The Pip install just says that everything is already installed. AUR might just be a wrapper for this one.

Flatpak is another story. When installing it, i don't even get a tray icon so i can't even open the settings. It seems it is missing some dependencies in there. Also when joining a Channel i did not get any overlay. I can't tell if it is something wrong with the settings or flatpak.

This is the relevant part of the log:

```
Gtk-Message: 10:22:30.418: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:22:30.418: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:22:30.418: Failed to load module "appmenu-gtk-module"
INFO:root:Flatpak compat mode started

** (discover-overlay:2): WARNING **: 10:22:30.558: gtk-layer-shell v0.7.0 may not work on GTK v3.24.33. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
ERROR:root:Unable to load file share/icons//hicolor/256x256/apps/discover-overlay-default.png
ERROR:root:Unable to load file share/icons//hicolor/256x256/apps/discover-overlay-default.png
INFO:root:Falling back to Systray : Namespace AppIndicator3 not available

(discover-overlay:2): Gtk-CRITICAL **: 10:22:30.561: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by trigg** [comment]
Flatpak is not completely up to par with other methods.

Not been able to successfully test:
- Wlroots with gtk-layer-shell
- AppIndicator (sys tray)
- RPC (`--configure` etc)

I'm not sure how KDE detects unresponsive windows but if it's accepting input then it is actually responsive.

**Comment by trigg** [comment]
So inexplicably I am now witnessing this. no closer to an answer just yet

**Comment by xzn** [comment]
It seems to be an issue between GtkLayerShell and KDE:

```python
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

gi.require_version('GtkLayerShell', '0.1')
from gi.repository import GtkLayerShell

GtkLayerShell.get_protocol_version()

win = Gtk.Window()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```

Shows the problem already

**Comment by trigg** [comment]
Interesting! So it may be a Plasma issue then

**Comment by trigg** [comment]
This needs testing again on latest git, as we've separated the two processes

**Comment by ThaSiouL** [comment]
Yup. Tested it on r38 and r40. The tray icon is gone though,

**Comment by trigg** [comment]
Closing this for now. Try running 'discover overlay configuration' and checking the systray is enabled. Open a new issue for it if you can't get it to show up
