### ISSUE TITLE
Broken on Plasma Wayland

### ISSUE THREAD

**Issue by baduhai** [trigg/Discover#217]
**Steps to Reproduce**
1. Open Discover Overlay

**Expected behavior**
The overlay opens and starts working.

**Problematic behavior**
Doesn't work, nothing happens. When running `flatpak run io.github.trigg.discover_overlay` I get the following:

```
WARNING:root:Discover overlay is currently running
WARNING:root:Sent RPC command
```

And weirdest of all, `flatpak kill io.github.trigg.discover_overlay` returns `error: io.github.trigg.discover_overlay is not running`. This only happens on plasma wayland, on x11 it works fine, though the system tray icon doesn't do anything.

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed

**Installation Method**
 - Flatpak

**Additional context**

**Comment by trigg** [comment]
My apologies on the delay. A known bug for Flatpak is the RPC/PID code simply doesn't work. I've resorted to using `--nolock` to force it to run a new instance each time.

**Comment by trigg** [comment]
For anyone more interested in fixing this `discover_overlay/discover_overlay.py` around line 271 (currently)

```
    try:
        with pidfile.PIDFile(pid_file):
            logging.getLogger().setLevel(logging.INFO)
            Discover(rpc_file, debug_file, line)
    except pidfile.AlreadyRunningError:
        logging.warning("Discover overlay is currently running")

        with open(rpc_file, "w") as tfile:
            tfile.write(line)
            logging.warning("Sent RPC command")
```

With only cursory testing it appears to always throw `AlreadyRunningError` for as long as the lock file exists in any state. Strongly suspect this has a lot to do with flatpak disallowing a check on the processes list.

For now I've changed the .desktop file when shipped in flathub to automatically add --nolock but it's worth noting that that simply means there's no RPC at all currently for flathub users.

**Comment by trigg** [comment]
Changed logic and pushed new testing version:
- Remove --nolock
- Detect flatpak environment
- to send RPC commands to a running instance use `--rpc`
- Assume new instance in flatpak if no `--rpc`
