### ISSUE TITLE
Click-Through not working in River WM

### ISSUE THREAD

**Issue by taylor85345** [trigg/Discover#219]
**Steps to Reproduce**

1. Install [River](https://github.com/riverwm/river), configure and log in. I use `river-git` from the AUR.
2. Start Discord and run `discover-overlay --configure`
3. Enable the Text Overlay
4. Attempt to interract with the desktop or any application via mouse.

**Expected behavior**
Mouse clicks should pass through the overlay to the underlying window.

**Problematic behavior**
Mouse input is not passed through.

**Desktop**
 - WM: [River](https://github.com/riverwm/river)
 - OS: Garuda Linux

**Installation Method**
 - AUR
 

**Additional context**
Overlay does not cover waybar (or presumably any other properly configured bar). Mouse interactivity with bar still works while Discover is active.

**Comment by trigg** [comment]
Interestingly... attempting to install this on my laptop requires I uninstall my current window manager, so this will need a bit more than a cursory package install on my part.

This sounds like river is either ignoring the XInputShape (can it even be called that in wayland?) or something in gtk-layer-shell is not translating well between wlroots environments.

**Comment by trigg** [comment]
Ah I take it back. As soon as waybar is running I get this issue.

**Comment by trigg** [comment]
And just like that, fresh run it works again.
