### ISSUE TITLE
Seeing double

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#224]
I'm now getting dual notifications. Top right corner and bottom right corner. 
Probably need to somehow check users don't already have a way of receiving notifications. 
End users are stupid.

**Comment by midget3111** [comment]
![Screenshot_2022-03-29_20-42-58](https://user-images.githubusercontent.com/964775/160694351-d8b937d7-be95-41e8-ad7e-3c9437ac91de.png)

**Comment by trigg** [comment]
No, just don't enable it if you have notifications ;_;
