### ISSUE TITLE
Speaker only mode with X11 leaves last speaker on screen

### ISSUE THREAD

**Issue by willwh** [trigg/Discover#227]
**Steps to Reproduce**
1 - Set `Display Speakers Only`
2 - Ensure `Force XShape` is enabled (I assume this is a default as I don't remember changing it)

**Expected behavior**
No users are displayed after speaking ends

**Problematic behavior**
If multiple people speak, or only a single person speaks, the last to speak person will remain on screen, so that a single user is always visible

**Desktop:**
 - OS: Fedora 35

**Installation Method**
Package manager
```
willwh@claymore [07:15:29 PM] [~] 
-> % sudo dnf list installed | grep discover
discover-overlay.noarch                           0.5.0-1.fc35                           @copr:copr.fedorainfracloud.org:mavit:discover-overlay
```

**Additional context**
I am not using Wayland, but the `X11` compositor.

**Comment by trigg** [comment]
Unable to reproduce but I do remember seeing this a few versions back. Which X11 compositor? I'd assume gnome if you're using Fedora?

**Comment by trigg** [comment]
Can't force Xshape if there's no X! :point_right::smiley: 

I think it was a redraw logic bug that I accidentally squashed since last stable release. Once we get a chance to test the new changes we'll get a new stable going out. Leave it open until we can confirm :)

**Comment by trigg** [comment]
hey @willwh  we've pushed 0.5.1 now, mind testing if this still occurs?

**Comment by willwh** [comment]
Oh this is awesome :) that does appear to have solved the issue, very nice!!
