### ISSUE TITLE
GTK Layer Shell not supported on Gnome 42 (but works)

### ISSUE THREAD

**Issue by nicokimmel** [trigg/Discover#229]
**Steps to Reproduce**
1. Open terminal
2. Type discover-overlay
3. See error

**Expected behavior**
It should open and display the overlay

**Problematic behavior**
When just typing it prints out the following error:

`WARNING **: 02:07:53.120: It appears your Wayland compositor does not support the Layer Shell protocol`
`INFO:root:GTK Layer Shell is not supported on this wayland compositor`
`INFO:root:Currently not possible: Gnome, Plasma, Weston`

But when I first switch into root or launch it via `sudo -u testuser discover-overlay` it does indeed work. That means that launching from a .desktop file needs a little workaround.

**Desktop (please complete the following information):**
 - Arch Linux (Gnome 42 on Wayland)

**Installation Method**
 - AUR

**Additional context**
/

**Comment by trigg** [comment]
This result is concerning. If they support GTK Layer Shell at all then it will pass the check of support and not get that error. Most likely your sudo-and-sudo-back approach is losing the wayland session environment variables and loading up in X11 mode... which I'm impressed then doesn't cause bigger problems for you.

None the less, Gnome continues to not support layer shell and trying to treat wayland sessions like X11 sessions is ... unpredictable.

**Comment by trigg** [comment]
https://github.com/wmww/gtk-layer-shell#supported-desktops

This is the official support list for layer shell, I'm closing this as there's no way to support Gnome without unsupported hacks
