### ISSUE TITLE
Default avatar are invisible in voice overlay

### ISSUE THREAD

**Issue by ServerBBQ** [trigg/Discover#234]
**Steps to Reproduce**
1. Join a voice chat with someone that has a default discord avatar
4. See that their avatar is invisible in the overlay

**Expected behavior**
In the voice overlay, a user's avatar appears in the overlay when they have a default avatar

**Problematic behavior**
When in the voice overlay, when a user has a default avatar, their avatar is invisible on the voice overlay

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) 
 - 
**Installation Method**
 - Flatpak

**Comment by trigg** [comment]
Looks like stable version 0.5.1 has made it to flatpak in the last few minutes. 

Would you mind testing again? I suspect the issue is still there but confirmation would help

**Comment by ServerBBQ** [comment]
Yup, issue is still in 0.5.1
