### ISSUE TITLE
Too many people in a voice room overflows off edges of screen

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#235]
**Steps to Reproduce**
Join a very busy room

**Expected behavior**
Uncertain, may give users options as this is a use-case I've not seen yet

**Problematic behavior**
In 'middle' view, list goes off top and bottom, otherwise list goes off opposite end of screen

**Desktop (please complete the following information):**
 Not mentioned in report

**Installation Method**
Not mentioned in report

**Additional context**
Brought in from a personal message received

**Comment by TheKodeToad** [comment]
![image](https://user-images.githubusercontent.com/57493648/164942803-3e4cc317-5575-4d30-99bb-de159ddb172b.png)
For me, it just cuts off.

**Comment by trigg** [comment]
Is the mute icon not lining up something that happens other than right now?

**Comment by trigg** [comment]
And sorry, yes, 'overflow' just means that it ignores the fact it's gone past an edge, cutting off is done by the fact there's nowhere past the end to draw, but it continues trying to draw into infinity if needed

**Comment by trigg** [comment]
![2022-04-23-221459_2560x1440_scrot](https://user-images.githubusercontent.com/535772/164947774-1d4d0134-cde7-4ea9-9f3d-e96d004c0e9d.png)

Update coming.

**Comment by trigg** [comment]
Fixed in latest git.
