### ISSUE TITLE
Permanent black overlay when a game disables the compositor after game start

### ISSUE THREAD

**Issue by zany130** [trigg/Discover#236]
**Steps to Reproduce**
1. enable force xshape
2. enable notifications
3. disable overlay while notification overlay is showing
4. See a permanent black overlay drawn on top of the game (this does show discord notifications but the overlay stays stay there at all times)

**Expected behavior**
Discord messages show on top of the game and disappear after the configured timeout time

**Problematic behavior**
A permanent black overlay is drawn over the game that does not disappear after messages time out.

**Desktop (please complete the following information):**
```
inxi -b
System:
  Host: Kiseki Kernel: 5.17.4-256-tkg-pds arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.4 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P4.86 date: 01/27/2022
CPU:
  Info: 6-core AMD Ryzen 5 2600X [MT MCP] speed (MHz): avg: 4119
    min/max: 2200/3600
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 510.60.02
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.1 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1080
    2: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.60.02
Network:
  Device-1: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 3.02 TiB (102.3%)
Info:
  Processes: 482 Uptime: 3h 28m Memory: 31.27 GiB used: 17.56 GiB (56.1%)
  Shell: fish inxi: 3.3.15
  ```

**Installation Method**
 - AUR (chaotic aur specify so I don't have to build)
 
 ```
 pacman -Qi discover-overlay
Name            : discover-overlay
Version         : 0.5.1-1
Description     : Yet another Discord overlay for Linux written in Python using GTK3
Architecture    : x86_64
URL             : https://trigg.github.io/Discover/
Licenses        : GPL3
Groups          : None
Provides        : discover-overlay
Depends On      : gtk3  python-gobject  python-pyxdg  python-requests  python-websocket-client  python-pidfile  python-cairo  python-pillow  python-xlib  dbus-python
Optional Deps   : gtk-layer-shell: Wayland support
Required By     : None
Optional For    : None
Conflicts With  : discover-overlay-git
Replaces        : None
Installed Size  : 3.23 MiB
Packager        : UFSCar HPC Builder <hpc.ufscar@chaotic.cx>
Build Date      : Sat 23 Apr 2022 09:36:14 AM EDT
Install Date    : Sat 23 Apr 2022 04:13:07 PM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Additional context**
For some reason, everything works as expected (no permanent black overlay) when the app is started after the game is running.

**Comment by trigg** [comment]
What Desktop is this on? Gnome, KDE, Xfce? What compositor?

**Comment by trigg** [comment]
KDE, just seen the convo, sorry

**Comment by MurdoMaclachlan** [comment]
I don't know exactly how this works, but when I first turned off compositing on Xfce, a number of apps (including the settings applet) got black bars around them that went away after they restarted. Someone logged [an Xfce bug report](https://gitlab.xfce.org/xfce/xfwm4/-/issues/281) a couple of years ago for something like this, the developer response was:

> It shows as black above because you turned the compositor off after the client was started. First and foremost, please don't do that, clients such as gtk applications cannot deal with the compositor being turned off and will shows a black area instead of the transparency expected.
>
> That said, the black area you show above in your screenshot is part of the client, some of it is used for resize handles, the rest is shadows.

**Comment by trigg** [comment]
Similar issue, good catch.

The major thing to note is I will probably enable-by-default and remove the option for `Force XShape` as there are no apparent side effects and it covers a whole bunch of edge cases... I'm confused it doesn't cover this one

**Comment by zany130** [comment]
Switched to an rx 6700xt and I am able to reproduce the issue there

**Comment by trigg** [comment]
Is this with 'Force XShape' on?

**Comment by zany130** [comment]
yes

**Comment by trigg** [comment]
Then I'm not really sure much more can be done on this. Disabling compositing mid-session in this manner isn't well supported by gtk and that's how we're drawing the overlay

**Comment by trigg** [comment]
If you're still watching this, it is worth testing with newer updates of KDE and Discover-overlay. I can no longer produce this issue

**Comment by zany130** [comment]
I can still reporduce in a fully up-to-date Garuda system (arch based) on kde with discover installed from the AUR. Run checked the box for showings test notifications and disabled the compositor while it is showing

**Comment by trigg** [comment]
Odd that AUR is out of date. I meant latest from git, which should get pulled in with https://aur.archlinux.org/packages/discover-overlay-git

**Comment by zany130** [comment]
i was using the non git aur

**Comment by trigg** [comment]
That's fair, that won't have my latest attempts to fix the issue though :)

**Comment by zany130** [comment]
I thought the flatpak was already at 5he latest version since i saw you pushed a new  i thought the flatpak was at the latest with that aur build and when i saw it hadn't been updated i tried the flatpak.


Works on the git air package though. It sometimes flickers a bit but only once from my testing (honestly didn't test to much since i now moved to Wayland)

**Comment by trigg** [comment]
Thanks for testing again!
