### ISSUE TITLE
Substitute dbus-python

### ISSUE THREAD

**Issue by NicolaSmaniotto** [trigg/Discover#239]
Hello, would it be possible to avoid using `dbus-python`? It does not register itself correctly as a system package when installed by a package manager, making Discover raise a `pkg_resources.DistributionNotFound` exception.

A workaround is to patch the setup.py to remove the dependency, but it would be better to avoid it entirely. Freedesktop suggests some alternatives [here](https://www.freedesktop.org/wiki/Software/DBusBindings/#dbus-pythonbasedondbus-glib), but there are more (like [dasbus](https://github.com/rhinstaller/dasbus))

**Comment by trigg** [comment]
does setup.py not install a version once it notices the lack of a system-wide version?

**Comment by NicolaSmaniotto** [comment]
Since I'm installing through the package manager (gentoo's portage), setup.py is not used to directly install the dependencies. We install them via portage, but `dbus-python` is not seen when the program searches for its dependencies at runtime.

As I said, just removing the check makes Discover work, but it would still be better to switch to an alternative, since the developers themselves suggest so.
