### ISSUE TITLE
Opt-In not working?

### ISSUE THREAD

**Issue by KelvinShadewing** [trigg/Discover#240]
When I first started Discover, it gave me a warning saying I was in too many servers, and using it in too many could get me banned, and that I should "opt in" to just a few servers, but does not say how. I found a setting with check boxes for servers I'm in, and checked just one of them, but the overlay still appears when I enter voice in other servers. How do I limit it to just one server? Why does using it in multiple servers risk me getting banned?

**Comment by trigg** [comment]
Hey! Depending on which version you're running the answer to this has changed drastically.

As with #134  the old method of finding the room the user was talking in was to ask about every single room and check the active user list until the user was found. This caused a LOT of calls in very short succession and Discord would hit a rate limit stopping you from using the service for a while. A different, previously unavailable, method of asking directly came to light and we moved to that, but for a while kept the warning & opt-in just in case it didn't fully fix the issue. If the opt in is there, and you can't use the voice rooms you've not opted in to then you're on an older version where it's needed. If the opt in is there but doesn't seem to do anything, you have the fixed version.

**Comment by KelvinShadewing** [comment]
Ohhhhh, I see now. OK then, I think I'm using the fixed version.
