### ISSUE TITLE
Reset config to default option

### ISSUE THREAD

**Issue by ServerBBQ** [trigg/Discover#241]
My first idea is to have a config reset button, so if you mess up in one of the configs(EX: accidentally pick a color you don't like), and you would like to do a reset, you just click a button to reset all the settings.

Another idea to add on top of that is to add a feature that if you shift click a setting, it pops up a confirmation dialog that asks something like "You shift-clicked <setting-name>, Do you want to reset <setting-name> to default". 

If you do add the shift-click reset in, you should probably put a note about it in the overview section

**Comment by trigg** [comment]
Interesting. I'm not certain I'd do per-item reset as an option but per config page would be doable.

**Comment by luni3359** [comment]
This is a good idea ❤️

**Comment by trigg** [comment]
I can't believe it took me this long to get around to this, my apologies.
