### ISSUE TITLE
Documentation - What issues remain with Plasma?

### ISSUE THREAD

**Issue by yaomtc** [trigg/Discover#243]
I am using 0.5.1.r9.gbb0819f-1 from discover-overlay-git on the AUR. The wiki is currently out of date, as "Input shape is ignored thus cannot click through" is no longer the case. 

* it stays above other windows
* no border
* custom overlay position works

The only issue I can see is that Plasma seems to think the Configuration window is not responding, even though it is. So the window becomes grayed, but I can still use it with no problem, albeit blandly.

**Comment by trigg** [comment]
The wiki is absolutely out of date. Good point. That page was before layer-shell integration was working on plasma so the only way to make it (partially) work was to force X11 mode in wayland Plasma.

We've been unable to reproduce the grayed window in Plasma ourselves so have no idea how to fix it yet.

I think in answer to this actual issue we need to chuck the wiki and use the [website](https://trigg.github.io/Discover/) as that can accept pull requests
