### ISSUE TITLE
Not showing who is talking when user don't have avatar

### ISSUE THREAD

**Issue by fjfalcon** [trigg/Discover#245]
**Steps to Reproduce**
Launch discover overlay with someone in room without avatar. 
When he will talk - there no green circle

**Expected behavior**
When someone talks - his avatar or nickname glowing

**Problematic behavior**
As a result - we don't know who talking...

**Desktop (please complete the following information):**
- Linux, ArchLinux

**Installation Method**
 - AUR

**Additional context**
If user adds avatar - everything works fine

**Comment by fjfalcon** [comment]
Also checked where is discover-overlay-default.png.  It's in /usr/share/icons/hicolor/256x256/apps/discover-overlay-default.png

**Comment by trigg** [comment]
Looks like it's already fixed in #234
