### ISSUE TITLE
Memory leak with text overlay

### ISSUE THREAD

**Issue by ServerBBQ** [trigg/Discover#246]
**Steps to Reproduce**
1. Enable text overlay for a channel
2. Enable show attachments
3. Send(or receive) a bunch of images in the channel that text overlay is set too
4. Notice that the ram usage of discover overlay goes up, and doesn't go back down

**Expected behavior**
Memory usage stays low

**Problematic behavior**
Memory usage stays high after a bunch of images are loaded in text overlay

**Desktop (please complete the following information):**
 - Debian 11 gnome

**Installation Method**
 - Flatpak

Screenshot of high memory usage:
![image](https://user-images.githubusercontent.com/76498501/168200434-fcca4a64-e929-4404-92cb-e44a39155ecc.png)

**Comment by trigg** [comment]
Yeah, there's currently no mechanism to free up image data once the image goes out of range. I can see how this is happening.

We'd need to go through occasionally cross-checking cached images with messages still in memory, and remove unreferenced ones. This isn't as simple as un-caching as soon as a message goes out of range as it can be referenced by multiple messages.

**Comment by trigg** [comment]
Coincidentally, as a tangent, the same thing will happen with user avatars if enough user turnover happens in a voice room. Albeit avatar images are usually smaller so it'd go unnoticed for much longer

**Comment by trigg** [comment]
Latest testing has a fix, need some general testing before we put this to stable
