### ISSUE TITLE
Freesync games

### ISSUE THREAD

**Issue by mrshroomy** [trigg/Discover#247]
Explain what actually happens, and how it differs from expectation
When discover overlay is used in games the game freesync doesnt work on Linux, it causes stuttering in bloodhunt masquerade but the game normally runs well with freesync

**Desktop (please complete the following information):**
 - KDE Plasma

**Installation Method**
 - AUR

**Comment by trigg** [comment]
It realistically is not possible to enable freesync with more than one window outputting to the display.

To fix this we'd need to rewrite from ground up to do library injection the same way mumble overlay does, requiring a C or rust rewrite
