### ISSUE TITLE
Coding standard is sub-par

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#25]
Having a large segment of the code relying on globals and global-scoped functions which pass around a bunch of contexts is absolutely not ideal.

Move all Socket & communication into a class. Narrow down global scoped to entry point only.

**Comment by midget3111** [comment]
Yes, I know I am at risk of getting the "possible troll" label again. But, If, and this is a big if... 
We do decide to go down the route of supporting other voice systems, would abstracting out the Discord specific stuff be a good thing to do along with this? if so I'll open another issue.

**Comment by trigg** [comment]
I'll close this now as although none of the code is perfect it is now considerably easier to start reading
