### ISSUE TITLE
Wayland crash

### ISSUE THREAD

**Issue by lologarithm** [trigg/Discover#250]
**Steps to Reproduce**
1. Updated to 22.04 which defaults wayland now.
2. Launching discover-overlay gives this error:
"NameError: name 'GtkLayerShell' is not defined"

The error comes from draggable_window_wayland.py , it first does a gi.require_version which succeeds but then trying to to `from gi.repository import GtkLayerShell` it throws the above error.

I have installed python3-gi so I should have the layer shell available, its possible this is some kind of weird pathing issue.

**Expected behavior**
Not crash

**Problematic behavior**
Crashes

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Installation Method**
 - git clone & pip

**Additional context**
Feel free to request any other logs or system information that would be helpful

**Comment by lologarithm** [comment]
Followup: https://github.com/wmww/gtk-layer-shell says `Layer shell is not supported on:    Gnome-on-Wayland`.. This might mean that we cannot use the overlay on ubuntu (without changing how the panel is created)

**Comment by lologarithm** [comment]
I do have gtk-layer-shell installed. I think this is an issue related to gnome-wayland and not the library itself

**Comment by lologarithm** [comment]
btw, I did this 
`sudo apt install gir1.2-gtklayershell-0.1` 

and now get 

```INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.6.3

** (discover-overlay:514477): WARNING **: 09:58:45.505: It appears your Wayland compositor does not support the Layer Shell protocol
INFO - discover_overlay.overlay - GTK Layer Shell is not supported on this wayland compositor
INFO - discover_overlay.overlay - Currently not possible: Gnome, Weston
```

**Comment by trigg** [comment]
Worth mentioning, as I'm about to close this. This isn't a crash this is a situation it can't work in and it intentionally closes here.

**Comment by goat865** [comment]
> however, `GDK_BACKEND=x11 discover-overlay` seems to stop the crashing

holy shit that worked, thank you :D
