### ISSUE TITLE
Problems trying to debug with VS Code

### ISSUE THREAD

**Issue by luni3359** [trigg/Discover#251]
**Steps to Reproduce**
1. Open VS Code
2. Have this in `.vscode/launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "discover_overlay"
        }
    ]
}
```
3. Press F5 to start the debugging process
4. The debugger starts working but then...
5. `/bin/python: No module named discover_overlay.__main__; 'discover_overlay' is a package and cannot be directly executed`

**Expected behavior**
The debugging starts

**Problematic behavior**
The program crashes, even though it does try to start 

**Desktop (please complete the following information):**
 - OS: KDE Neon (Ubuntu-based)

**Installation Method**
 - pip (tried this with discover-overlay installed and when removed)

**Additional context**
The program doesn't crash if you create a `__main__.py` file inside the `discover_overlay` folder, but it also stops dead because `__main__.py` is empty once it reaches it.

**Comment by trigg** [comment]
So you need a __main__.py file with contents that start the program.

Try:
```
from .discover_overlay import *
entrypoint()
```

This will start the program whenever __main__.py is called. I don't know if this will totally fix it unless there's some magic ensuring it's using the local copy module and not installed-by-pip module but I don't know vscode enough to know the answer there.

**Comment by luni3359** [comment]
That works, thanks! Why doesn't the project itself have a `__main__.py` though? 

More over, how is it working at all without the file? 😮 I'm still somewhat new to python so this is news to me. On this [project](https://github.com/luni3359/koa-bot/tree/master/koabot) I've worked on I had to stuff everything into the `__main__.py` file because I couldn't figure out how to "redirect" `__main__.py` to the actual file that starts up everything.

**Comment by trigg** [comment]
'normal' usage would be the 'entry_point' defined in [setup.py](https://github.com/trigg/Discover/blob/master/setup.py#L37) which calls `discover_overlay.discover_overlay.entrypoint()` This doesn't apply within code as the entry point is an install-specific rule as I understand.

As for 'redirecting' out of main, just import the bits you want to call from `__main__` similar to my previous comment, then call the function or use the variable you've imported

**Comment by trigg** [comment]
That said, as it seems to be in our favour, I think I'll commit the `__main__` so that this is one less hurdle to entry

**Comment by luni3359** [comment]
Thank you! I really appreciate the lessons. Hopefully we can talk more in the future.

**Comment by trigg** [comment]
Feel free to ask anything! I don't know lots but I may be able to help
