### ISSUE TITLE
Gamescope session on deck no longer shows overlay

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#253]
**Steps to Reproduce**
1) Start fresh deck session
2) Start Discover overlay
3) Start Discord & join room

**Expected behavior**
Voice overlay shows

**Problematic behavior**
No overlay shows

**Desktop (please complete the following information):**
- Steam deck beta

**Installation Method**
- Flatpak

**Additional context**
Rather new issue as was working previously

**Comment by trigg** [comment]
From a quick test, killing mangoapp shows the overlay correctly. It appears Mangohud no longer closes window when turned to setting 0.

**Comment by trigg** [comment]
For anyone with SSH access and the inclination, ending the `mangoapp` process will allow this overlay to work again until next reboot... but will disable the performance HUD

**Comment by trigg** [comment]
For anyone with SSH access and the inclination, ending the `mangoapp` process will allow this overlay to work again until next reboot... but will disable the performance HUD

**Comment by trigg** [comment]
This is fixed in latest steam deck beta.

**Comment by midget3111** [comment]
Can confirm
