### ISSUE TITLE
Force XShape in gamescope mode doesn't clear previous render artifacts

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#254]
**Steps to Reproduce**
1) Start gamescope
2) run discover-overlay in DISPLAY of gamescope with GAMESCOPE_WAYLAND_SESSION and without WAYLAND_SESSION
3) in 'Core' tick 'Force XShape'
4) Move position of or change contents of overlays

**Expected behavior**
Old visual data is cleared after move or change

**Problematic behavior**
XShape is used to mask drawing calls so that no excess processing of image is done, but gamescope does not mask the drawing using an xshape so old pixel data is used where it would normally be masked.

**Desktop (please complete the following information):**
- Gamescope / SteamDeck

**Installation Method**
Flathub

**Additional context**
Ignore user preference for XShape in gamescope mode, while gamescope mode absolutely is an X11 session it should not attempt to treat it like a normal X11 session

**Comment by midget3111** [comment]
This raises the question of whether we still need force X shape as an option?

**Comment by trigg** [comment]
In X11 mode normally it really should be on by default, in gamescope and wayland it is not the correct option

**Comment by trigg** [comment]
I suppose I need to account for really edge cases of WMs that don't actually accept XShape... I'm sure there are more
