### ISSUE TITLE
Floating overlay location doesn't work properly with multiple monitors

### ISSUE THREAD

**Issue by xzn** [trigg/Discover#256]
With multiple monitors,

Set Floating option for Overlay Location,

The Place Window box always shows up in the primary monitor and cannot be moved to other monitors. The monitor which the overlay actually appears on can only be changed in Anchor to edge options.

The overlay also no longer pass through mouse actions rendering the entire monitor the overlay is on unusable until the overlay is killed, after changing Overlay Location options.

Edit:

On Wayland + KDE + Nvidia

discover-overlay-git From AUR just a moment ago so [4c07473](https://github.com/trigg/Discover/commit/4c074737aaad6b0c54c618778718d9d4cd20eba2) i guess?

**Comment by midget3111** [comment]
Hello, I see you've decided against using our default  issue template. Please provide the following information so that we can help:
Version of Discover-Overlay 
Installation method of Discover-Overlay 
Desktop environment
X11/Wayland/gamescope 

Many thanks

**Comment by xzn** [comment]
Thanks for the quick response! updated initial comment.

**Comment by trigg** [comment]
Thanks for the report. Floating windows haven't had much attention in a while, I'm looking into this now

**Comment by trigg** [comment]
So this is a two issues in one.

1) Wayland desktops are not one large display split among multiple monitors, as in X11. 
 Two displays 1920x1080 side by side you'd place a window at x position 1921 to put it on 2nd display. This is obviously not the case in wayland
 2) Plasma loses the input_shape when moving a window to another monitor. This might be a bug in Plasma, might be a bug in GTK, but I can patch this one right away.

**Comment by trigg** [comment]
Latest commit has some attempts at fixing. Update and give it a whirl, let me know how it comes out.

**Comment by xzn** [comment]
Both issues seem to have been fixed. Thank you very much!
