### ISSUE TITLE
[Suggestion] Better view of Mute and Deafen icons

### ISSUE THREAD

**Issue by matmicha** [trigg/Discover#257]
maybe put a dark background between icon and pfp, and put a glow around the icon ?

**Comment by trigg** [comment]
These are drawn here

Mute
https://github.com/trigg/Discover/blob/8b507a5323b2c46080bc1f39871ec009272c535d/discover_overlay/voice_overlay.py#L638
Deaf
https://github.com/trigg/Discover/blob/8b507a5323b2c46080bc1f39871ec009272c535d/discover_overlay/voice_overlay.py#L695

and Cairo docs are here
https://pycairo.readthedocs.io/en/latest/reference/context.html#cairo.Context

**Comment by matmicha** [comment]
nice, I'll take a look at it !

**Comment by matmicha** [comment]
nice I'll take a look at it !

**Comment by matmicha** [comment]
made a pull request for this feature : https://github.com/trigg/Discover/pull/259

**Comment by trigg** [comment]
Marking as complete. Thank you!
