### ISSUE TITLE
Use server custom profile picture

### ISSUE THREAD

**Issue by SDK4rma** [trigg/Discover#258]
don't know if it's possible to get the profile picture we set for a certain server when we're in a vocal channel of it ?

**Comment by trigg** [comment]
This has been talked about before but I don't know how people envision it looking. Just a title above list with server icon & channel name?

**Comment by matmicha** [comment]
ah sorry I described the issue poorly 
I was talking about the Discord Nitro allowing you to have custom server profiles and to change your profile picture depending on the server you're on 

the idea would be to display the custom profile picture of each user if they have set it

**Comment by trigg** [comment]
Ah yes, I didn't even know that was a feature

**Comment by matmicha** [comment]
struggling a bit on this, do you know where I could get the current voice guild ID ?

**Comment by trigg** [comment]
https://github.com/trigg/Discover/blob/8b507a5323b2c46080bc1f39871ec009272c535d/discover_overlay/voice_overlay.py#L490

Here we decide if we have an avatar image for the user and if not request we download one. At this point we don't know the guild id and probably don't even know channel id, but could grab that from  `discover.connection.current_voice`

**Comment by trigg** [comment]
it's quite likely, but I can;t test to find out, that this information is passed in when we get any new user data.

If you're up to finding out you could add `print(j)` before https://github.com/trigg/Discover/blob/8b507a5323b2c46080bc1f39871ec009272c535d/discover_overlay/discord_connector.py#L375

and see what new user information this reveals. When you enter a new channel it should print a long line of info about the channel and participants in chat

**Comment by matmicha** [comment]
I found a way to get the guild ID, it's all OK
... but the feature also needs the guild avatar ID of the user

 ---

> and see what new user information this reveals. When you enter a new channel it should print a long line of info about the channel and participants in chat

about this, I found informations about current channel data through `'cmd' : 'GET_CHANNEL'` : 
the array `'voice_states'` displays all the users logged in the voice channel and their data

unfortunately, there isn't the guild specific avatar ID here, I'm still searching

**Comment by trigg** [comment]
This happens a lot, the api used is incomplete and often features get left out of it. Good luck on finding it

**Comment by matmicha** [comment]
yeah, I created a Feature Request on the Discord API GitHub to add this guild avatar ID to the RPC 
https://github.com/discord/discord-api-docs/discussions/5177

wait and see ...

**Comment by trigg** [comment]
I believe we're not about to see this changed, will close until anything happens on the other end
