### ISSUE TITLE
The overlay looks like a huge black square when the compositor is disabled

### ISSUE THREAD

**Issue by luni3359** [trigg/Discover#26]
When playing a game that disables the compositor, the overlay is turned into a huge chunk of black space that covers off part the screen on the side it is set to be at.

![overlay_bug](https://user-images.githubusercontent.com/16832398/94352444-a44bf580-002a-11eb-9d7e-3cc34e8ec1be.png)

**Comment by trigg** [comment]
I hadn't considered the case that compositing state would change mid-run. Thanks for the heads up

**Comment by trigg** [comment]
Would you mind trying the latest commit? Also great choice of game

**Comment by luni3359** [comment]
Thanks, by the way, your commit absolutely fixes it.
