### ISSUE TITLE
Username length limit

### ISSUE THREAD

**Issue by matmicha** [trigg/Discover#268]
I had the idea of an option to limit the length of the usernames. 
I'm currently coding this, but I don't know where to put the option in the settings (in which "voice settings" column ?) 
The settings would be a checkbox to toggle length limit + an adjustment field to set the max characters length (from 10 to 32). 

With the new Glade interface I'm pretty lost, I'll search how I can put it in (do you recommend me using the Glade app ?)

**Comment by trigg** [comment]
Interesting idea! We use the glade app to edit the gui, the hope was to make it more accessible for anyone wanting to change gui.

For now, just write the discover_overlay.py sections.

- read config and pass bool & number to voice_overlay
- in voice_overlay limit length if necessary 

The settings screen code & glade change can be done after that works. Overlay half will pick up manual edits to config so test it with manual edits like I do :P

**Comment by matmicha** [comment]
okay thanks, I'll give it a go after work to test it !


> I wonder if discord has a max limit?

indeed, the username limit on Discord is 32 characters, that's why I chose a 10-32 range :wink:

**Comment by matmicha** [comment]
> looking again, if the limit is already 32, don't use a tick box at all and just have it default to 32 length on a slider

that's a nice workaround, I'll try that instead

**Comment by trigg** [comment]
Merged it in, thanks!
