### ISSUE TITLE
Guru package missing psutil dependencies

### ISSUE THREAD

**Issue by Person1873** [trigg/Discover#271]
**Steps to Reproduce**
1. Install via emerge `emerge discover-overlay`
2. attempt to configure `discover-overlay --configure`
3. error shown as missing psutil library

**Expected behavior**
I would expect the configurator to pop up

**Problematic behavior**
no window is spawned and i get an error message in the console
```
`Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/discover-overlay", line 33, in <module>
    sys.exit(load_entry_point('discover-overlay==0.6.0', 'console_scripts', 'discover-overlay')())
  File "/usr/lib/python-exec/python3.10/discover-overlay", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/usr/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 21, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil' distribution was not found and is required by python-pidfile`

```
**Desktop (please complete the following information):**
 - Gentoo

**Installation Method**
 - emerged from the guru package repository

**Additional context**
after installing the dependency, i get another error which may or may not be related
````
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.6.0
INFO - discover_overlay.autostart - Autostart info : desktop /usr/share/applications/discover_overlay.desktop auto None
INFO - discover_overlay.autostart - Autostart info : desktop /usr/share/applications/discover_overlay_configure.desktop auto None
INFO - discover_overlay.settings_window - Falling back to Systray : Namespace AppIndicator3 not available

(discover-overlay:2444): Gtk-ERROR **: 21:32:41.325: failed to add UI: Failed to open file “/usr/lib/python3.10/site-packages/discover_overlay/glade/settings.glade”: No such file or directory
zsh: trace trap  discover-overlay --configure
````

**Comment by theS1LV3R** [comment]
It seems the source uploaded to pypi under v0.6.0 is missing the glade config files, while the source release from github has it.

**Comment by Person1873** [comment]
thanks zoe
i did find the glade settings.conf on github as was able to shoehorn it in
place.
the config page loaded correctly once i did that.
i havent yet tested if the overlay is working as expected

**Comment by trigg** [comment]
My apologies on not replying sooner. Can you check to see if the site-packages for this project contains a locales directory too? It should be alongside the glade directory

**Comment by Person1873** [comment]
Hi Trigg

please see below tree output of the installed directory
to simply anawer the question, no, the locale directory is not present

/usr/lib/python3.10/site-packages/discover_overlay
├── autostart.py
├── discord_connector.py
├── discover_overlay.py
├── draggable_window.py
├── draggable_window_wayland.py
├── glade
│   └── settings.glade
├── image_getter.py
├── __init__.py
├── __main__.py
├── notification_overlay.py
├── overlay.py
├── __pycache__
│   ├── autostart.cpython-310.opt-1.pyc
│   ├── autostart.cpython-310.opt-2.pyc
│   ├── autostart.cpython-310.pyc
│   ├── discord_connector.cpython-310.opt-1.pyc
│   ├── discord_connector.cpython-310.opt-2.pyc
│   ├── discord_connector.cpython-310.pyc
│   ├── discover_overlay.cpython-310.opt-1.pyc
│   ├── discover_overlay.cpython-310.opt-2.pyc
│   ├── discover_overlay.cpython-310.pyc
│   ├── draggable_window.cpython-310.opt-1.pyc
│   ├── draggable_window.cpython-310.opt-2.pyc
│   ├── draggable_window.cpython-310.pyc
│   ├── draggable_window_wayland.cpython-310.opt-1.pyc
│   ├── draggable_window_wayland.cpython-310.opt-2.pyc
│   ├── draggable_window_wayland.cpython-310.pyc
│   ├── image_getter.cpython-310.opt-1.pyc
│   ├── image_getter.cpython-310.opt-2.pyc
│   ├── image_getter.cpython-310.pyc
│   ├── __init__.cpython-310.opt-1.pyc
│   ├── __init__.cpython-310.opt-2.pyc
│   ├── __init__.cpython-310.pyc
│   ├── __main__.cpython-310.opt-1.pyc
│   ├── __main__.cpython-310.opt-2.pyc
│   ├── __main__.cpython-310.pyc
│   ├── notification_overlay.cpython-310.opt-1.pyc
│   ├── notification_overlay.cpython-310.opt-2.pyc
│   ├── notification_overlay.cpython-310.pyc
│   ├── overlay.cpython-310.opt-1.pyc
│   ├── overlay.cpython-310.opt-2.pyc
│   ├── overlay.cpython-310.pyc
│   ├── settings_window.cpython-310.opt-1.pyc
│   ├── settings_window.cpython-310.opt-2.pyc
│   ├── settings_window.cpython-310.pyc
│   ├── text_overlay.cpython-310.opt-1.pyc
│   ├── text_overlay.cpython-310.opt-2.pyc
│   ├── text_overlay.cpython-310.pyc
│   ├── voice_overlay.cpython-310.opt-1.pyc
│   ├── voice_overlay.cpython-310.opt-2.pyc
│   └── voice_overlay.cpython-310.pyc
├── settings_window.py
├── text_overlay.py
└── voice_overlay.py

2 directories, 53 files

**Comment by trigg** [comment]
Okay, so for one reason or another the 'package_data' is not getting shipped. I'm not at all familiar with portage, so I'm not sure what exactly is wrong yet.

On the original issue, we need to remove psutil/pidfile as it's no longer actually used.

**Comment by trigg** [comment]
https://pypi.org/project/discover-overlay/#files

First thing I've noticed is that the `.tar.gz` does not infact ship those directories. The `.whl` does and that's what I've been using, but I'm unsure about if that would work for this use case

**Comment by trigg** [comment]
Looking like [this](https://github.com/pypa/setuptools/issues/1461#issuecomment-954725244) is the problem. The source was not being made with `package_data` as I was using `include_package_data`.

**Comment by NicolaSmaniotto** [comment]
Hi, I'm the maintainer of the package in ::guru.

First of all sorry for the issues. I'm changing the ebuild to use the github tarballs, as pypi is missing those files.

It should be fixed the next time the repo is updated.

As a side note @Person1873, if something like this were happen again please open a bug report on [bugs.gentoo.org](https://bugs.gentoo.org/) or email me directly (maintainer information is available with the ebuild inside metadata.xml), since github issues do not ping us.

**Comment by trigg** [comment]
Thanks for dropping in with extra details.

**Comment by trigg** [comment]
> First of all sorry for the issues. 

In fairness to you, this is my fault for not testing the source builds simply because I didn't think anyone used them. Sorry about that.
