### ISSUE TITLE
[QA] SetuptoolsDeprecationWarning

### ISSUE THREAD

**Issue by NicolaSmaniotto** [trigg/Discover#272]
**Steps to Reproduce**
1. Compile Discover with setuptools

**Expected behavior**
No warning should be printed

**Problematic behavior**
Setuptools prints three warnings:
```
 Installing 'discover_overlay.glade' as data is deprecated, please list it in `packages`.
 Installing 'discover_overlay.locales.cy.LC_MESSAGES' as data is deprecated, please list it in `packages`.
 Installing 'discover_overlay.locales.en.LC_MESSAGES' as data is deprecated, please list it in `packages`.
```

**Desktop:**
 - OS: Linux (Gentoo)

**Installation Method**
 - OS package manager (Portage)

**Additional context**
Python version: 3.10.5
Setuptools version: 62.6.0
Probably related: https://stackoverflow.com/questions/72363601/how-to-interpret-the-package-would-be-ignored-warning-generated-by-setuptools

**Comment by trigg** [comment]
Thank you for the detail here, that's super helpful and I'd found completely different answers that I wasn't sure about from other sources.

So we think re-add `include-package-data=True` and change to `packages=find_namespace_packages()`?

**Comment by NicolaSmaniotto** [comment]
> So we think re-add `include-package-data=True` and change to `packages=find_namespace_packages()`?

Yes,  https://github.com/trigg/Discover/commit/d6eda5bf0281dd96cdce65286e74fe5e87305dfe fixes it
