### ISSUE TITLE
Some core settings don't save on Discover reboot

### ISSUE THREAD

**Issue by matmicha** [trigg/Discover#274]
When I change one of these two settings in the Core tab of configuration, it resets back to off when I restart Discover (or my PC).
![image](https://user-images.githubusercontent.com/16545424/185691181-5f749f5f-f57d-41f6-8c6d-b17f117e7cdc.png)
It keeps me from launching Discover on PC startup ...

**Comment by trigg** [comment]
Latest commit should fix the `Minimized` option but `Configuration on Startup` should be working. Try run `discover-overlay --configure` from command line and grab the two lines like so

`INFO - discover_overlay.autostart - Autostart info : desktop /home/user/.local/share/applications/discover_overlay.desktop auto /home/user/.config/autostart/discover_overlay.desktop`

The last arg should be `None` or a file path.
