### ISSUE TITLE
Game Lag when using Papirus Icons

### ISSUE THREAD

**Issue by Macabre215** [trigg/Discover#275]
Activating the mic in Discord and having the overlay enabled causes the entire desktop, including videos and games, to hang for 0.5-1 seconds. I have tried replicating this problem on multiple distros (Fedora, Ubuntu, Debian, Arch, Manjaro, Opensuse) and desktop environments (Gnome, KDE, Cinnamon, XFCE, Budgie). It seems to ONLY happen with the following: 1. Gnome DE and 2. Papirus icons. If I use any other icon pack, it fixes the issue. Also, I tried using installing Discover Overlay through Flatpak and git. Both have the same issue.

Any idea on how to fix this or what would cause it? Papirus is my favorite icon pack, so I'm hoping to resolve this so I can go back to using it on the Gnome desktop.

**Comment by trigg** [comment]
Thanks for the report. I have no idea how an icon theme could cause this but we're looking to get a few tests run with this new information soon to see what might cause it.

**Comment by trigg** [comment]
So far I'm unable to reproduce this issue.

Setup:
Arch linux
Gnome on Xorg
Discord & Discover-overlay open, in channel and using mic
Papyrus icon theme set
Running starbound
Running `top` on the side

**Comment by Macabre215** [comment]
I might have jumped the gun before looking into this further. I did more digging, and it seems to be an issue with Discord, 
Papirus, and the appindicator Gnome plugin from as far back as 2019. 

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/171

This problem has nothing to do with Discover Overlay. I can go ahead and close this issue if you like.

**Comment by trigg** [comment]
No problems, good find on that. I hadn't considered the appindicator plugin and on testing it does appear to be the missing part of the puzzle. 

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/171#issuecomment-870951306

Looks like the answer could be : 
- Don't use Papirus
- Don't use Gnome
- Don't use AppIndicator extension
 or 
- Use latest AppIndicator extension.
