### ISSUE TITLE
Can't save settings or view the whole window.

### ISSUE THREAD

**Issue by fugohan** [trigg/Discover#276]
**Steps to Reproduce**
1. Go to 'Tray'
2. Click on 'Settings'
4. See an error

**Expected behavior**
Window I can see the full content. 

**Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS

**Installation Method**

- pip

**Additional context**

![image](https://user-images.githubusercontent.com/46691165/187314400-94a813f9-c132-45e4-bc3a-91df487ea152.png)

**Comment by trigg** [comment]
That looks like a very old version of the settings. If the install from pip is recent then it looks like you also have an older version installed alongside, I'd advise checking `which discover-overlay` in a terminal to see where it is installed
