### ISSUE TITLE
Regression: can only be displayed on the first monitor

### ISSUE THREAD

**Issue by sereinity** [trigg/Discover#278]
**Steps to Reproduce**
1. Run sway (my desktop environment)
2. Have multiple monitor
3. Give focus on second monitor
4. Start discover

**Expected behavior**
Usually the overlay is displayed on the monitor having the focus when started.

**Problematic behavior**
Since v0.6.2 (I was on v0.5.3) discover can only by displayed on the first monitor. I also tried to run configuration to change the overlay placement, but I can't drag it out of the first monitor.

**Desktop (please complete the following information):**
 - Linux (arch)
 - Sway

**Installation Method**
 - AUR

**Additional context**
Usually I start it via wofi ; I have the same behavior from the command line, no relevant log regarding this issue.

**Comment by midget3111** [comment]
Hey, thanks for the report.

Have you specified it to display on your second monitor in the Discover-Overlay configuration?

**Comment by sereinity** [comment]
> Hey, thanks for the report.
> 
> Have you specified it to display on your second monitor in the Discover-Overlay configuration?

As my monitor has a really strange name (an hexcode) I did't recongnized the setting as a "select your monitor", thank you to have politely asking to check again settings ;)

I'm good with that, thank again and sorry for the useless trouble, I'm closing the issue.

**Comment by midget3111** [comment]
No problem, glad to be able to help! :D
