### ISSUE TITLE
Link to usage is not clear on the website

### ISSUE THREAD

**Issue by hibiii** [trigg/Discover#280]
**Steps to Reproduce**
1. Go to [the GitHub page](https://github.com/trigg/Discover)
2. Follow through the 'User website' link under the preview image

**Expected behavior**
Being presented with instructions and other information, or a clearly labeled link to a page on how to use Discover.

**Problematic behavior**
The links to the "Using Discover" page are unclear - they are worded as if they are for a install guide, thusly can be overlooked by an user who has already noticed the install steps.

**Comment by midget3111** [comment]
All displays correctly here. Please screenshot what you are seeing!

**Comment by Hibiii** [comment]
![image](https://user-images.githubusercontent.com/69405847/192150386-6eba98d7-44d6-40cf-a5df-941955970aaf.png)

**Comment by trigg** [comment]
The `Desktop` and `Steam deck` links below first image should be instruction, do these not work for you?

**Comment by Hibiii** [comment]
It's not my fault it's not clear. The GitHub page has instructions to install it, so it's not unrealistic someone would overlook the "Try on desktop and handheld" paragraph while looking for instructions.
