### ISSUE TITLE
Avatar Opacity doesn't work properly

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [trigg/Discover#285]
**Steps to Reproduce**
1. Voice > Avatar Opacity slider
2. Use slider

**Expected behavior**
Avatar Opacity to be a slider that changes the visibility of the profile picture and its accompanying text. From 0% to 100%

**Problematic behavior**
It doesn't make a difference on the opacity of the avatar icons or the text, when the slider is at the minimum value (0.5) some of them disappear entirely and others are discoloured, some have no effect.

**Desktop (please complete the following information):**
 - OS: Arch Linux, present in both Stable and Git

**Installation Method**
 - AUR, issue is present in both Stable and Git

**Additional context**
Its confusing for me to know if what I'm describing is a bug or is simply a missing feature.

**Comment by trigg** [comment]
What you're describing is unexpected behavior for the user but is absolutely what happened to me during testing too. I spent ages trying to triage this before deciding a low-end cap of 50% made it least obvious that this didn't work exactly as the user would expect. 

First thing to check is if your option "Core -> Force XShape" is enabled, as this will absolutely mess with this setting. 

As for the discolouring, all the drawing methods I found in Cairo ended up discolouring the image slightly with this setting.

This is certainly a bug I simply don't know how to work around it right now.

**Comment by trigg** [comment]
I should probably add if you're using X11 without a compositor (Like I do usually) this setting is actually doing nothing at all

**Comment by CoWinkKeyDinkInc** [comment]
Yeah turns out the problem was a KDE setting that disables compositing when I have a video game open like CSGO for example. With compositing always on, the opacity works like it should. Force XShape doesn't make a difference in opacity, but it seems it doesn't have anti aliasing so I left that off. 

The icon opacity still has a small visual issue, not sure if its possible but it the icons need to be darkened a bit when they are behind bright backgrounds like white and grey. This works well enough for me at the moment, thanks for the help!

**Comment by trigg** [comment]
Closing for now.
