### ISSUE TITLE
Autostart entries don't get added

### ISSUE THREAD

**Issue by epic0421** [trigg/Discover#286]
**Steps to Reproduce**
1. Go to the Core section in Discover Overlay Configuration
2. Tick Run Overlay on Startup and/or Run Configuration on Startup
3. Check the folder `~/.config/autostart`
4. The .desktop entries aren't added

**Expected behavior**
When the options of running the overlay on startup and/or running the configuration on startup are ticked, I expect the entries to be added to `~/.config/autostart`

**Problematic behavior**
The entries never get added to `~/.config/autostart`

**Desktop (please complete the following information):**
 - KDE Plasma on Arch Linux

**Installation Method**
 - Flatpak

**Comment by trigg** [comment]
Flatpak autostart currently doesn't work, and most likely it won't edit the host `~/.config/autostart` 

Some documentation is here https://github.com/flatpak/flatpak/issues/118 but frankly I haven't got a clue how I'm meant to use it right now.

I don't know the mechanism used but it could be interesting if this works in steam deck game mode.

**Comment by trigg** [comment]
https://github.com/flathub/io.github.trigg.discover_overlay/issues/15

I'm moving the issue over to flathub and closing this out.
