### ISSUE TITLE
Asset issues compared to AUR package

### ISSUE THREAD

**Issue by epic0421** [trigg/Discover#287]
**Expected behavior**
Flatpak assets should match the AUR version.

**Problematic behavior**
System tray icons for the flatpak version (left) are more blurry than the AUR version (right).

KDE hidden icons menu on taskbar
![2022-11-11_02 16 23](https://user-images.githubusercontent.com/85042398/201320855-88acc9a0-7faf-4a04-ae47-50700cb18ae5.png)

KDE System tray
![2022-11-11_02 15 32](https://user-images.githubusercontent.com/85042398/201320887-b271704e-89ec-484a-a1c0-763ac9115442.png)

Missing assets for the flatpak version compared to the AUR version.

Flatpak:
![2022-11-11_02 18 23](https://user-images.githubusercontent.com/85042398/201321467-9de3ad91-8c63-4dce-9818-939bf0777086.png)

AUR:
![2022-11-11_02 18 04](https://user-images.githubusercontent.com/85042398/201321566-1e60c78f-eb30-4066-9ce3-a25df5416d03.png)

Discover Overlay Configuration icon is missing on the flatpak version. Icon is present on the AUR version.
![2022-11-11_02 22 57](https://user-images.githubusercontent.com/85042398/201321857-3d30cab9-6062-4446-b621-1afa19007cb0.png)

**Desktop (please complete the following information):**
 - OS: KDE Plasma on Arch Linux

**Installation Method**
 - Flatpak

**Comment by trigg** [comment]
Good catch on the system tray icon quality. Very likely related

**Comment by trigg** [comment]
Fixed by all my tests. Reopen if it reoccurs!
