### ISSUE TITLE
Discover breaks adaptive sync (G-sync compatible/Freesync)

### ISSUE THREAD

**Issue by Cubevoid** [trigg/Discover#290]
**Steps to Reproduce**
1. Enable G-sync compatible on a monitor that supports it, and in the Nvidia settings app. Haven't tested it with AMD/Freesync
2. Check "Enable G-SYNC/G-SYNC Compatible Visual Indicator"
3. Test to see if adaptive sync is working, e.g. using VRRTest https://github.com/Nixola/VRRTest/releases/tag/v2.0.0
4. Open Discover
5. Open VRRTest again

**Expected behavior**
Adaptive sync should still be working with Discover running

**Problematic behavior**
As soon as Discover is running, adaptive sync stops working

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS

**Installation Method**
 - flatpak
 - pip (stable)

**Additional context**

**Comment by trigg** [comment]
As it currently stands this is fairly simple. We cannot support Freesync or un-redirect modes. 

This overlay is drawn as a X11 window or a Wayland shell and in both cases it means that any VRR application cannot enable VRR. For VRR to work the game/app needs to be the only window outputting to the screen and it is by default disabled once more than one window is being drawn.

This would require a from-scratch rewrite and if it ever gets done it will be done over on https://github.com/trigg/discern and not in python
