### ISSUE TITLE
Option to hide icons?

### ISSUE THREAD

**Issue by Matombo** [trigg/Discover#291]
Is there an option to only show usernames and hide the icons?

**Comment by trigg** [comment]
Not yet, but it is possible I can add it

**Comment by trigg** [comment]
Pushed in latest commit. 

This will need extra testing before I call it stable as it was a change to the core rendering spaghetti.

I'll mark this as complete only after I'm sure it's not breaking anything else

**Comment by trigg** [comment]
No bugs filed and no errors seen by testers, closing now
