### ISSUE TITLE
Flatpak: org.gnome.Platform branch 42 is end-of-life

### ISSUE THREAD

**Issue by cprin21** [trigg/Discover#292]
On Flatpak:
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.trigg.discover_overlay

Assuming that they only support two branches at a time - current which is 44 at the moment and the prior one 43.

**Comment by cprin21** [comment]
> Issue also mentioned here: [flathub/io.github.trigg.discover_overlay#7](https://github.com/flathub/io.github.trigg.discover_overlay/issues/7)

Apologies, closing this issue as it is a redundant report of the quoted and linked issue.

**Comment by trigg** [comment]
Thank you, as I do not get notification on flathub repository this is what alerted me to the problem
