### ISSUE TITLE
Feature request: Speaker Grace Period

### ISSUE THREAD

**Issue by Hubro** [trigg/Discover#294]
First of all, great job removing the only remaining thing I missed from gaming on Windows :smile: :heart: 

Discover is freaking amazing, but I have one use case where it could be better.

I often sit in Discord rooms with 25-50 people (raiding in World of Warcraft) which means I absolutely *need* to have `Show Speakers Only` enabled. However, people pop up as they speak, then they immediately disappear, often before I have time to see who it was.

What would be amazing is to add a supplementary option called `Speaker Grace Period`. This field would allow extra time in seconds where speakers would be visible before they disappear. This could be set to something like 3 seconds to give the user time to read the names of speakers before they disappear, or it could be set to something like 10-30 seconds to give a persistent view of active speakers. (In a raid group, the majority of participants are often only there to hear raid calls.)

---

(After that, the only thing remaining is to make a Vulkan implementation so the overlay can be used in exclusive full screen games :grin:)

**Comment by trigg** [comment]
Thank you for the report & pull request! I've added a 1 FPS timer to voice chat to redraw. Shouldn't make any notable difference to performance but does ensure people drop off the list correctly

**Comment by Hubro** [comment]
Installed `discover-overlay-git v0.6.3.r12.gaf5c569-1` from AUR now and tested it a bit, works freaking flawlessly :grin: :rocket:

**Comment by trigg** [comment]
Glad to hear! I have to give you credit for the feature.
