### ISSUE TITLE
Wayland Gnome 44 Crash Trying To Place Window In Configuration

### ISSUE THREAD

**Issue by cprin21** [trigg/Discover#298]
**Steps to Reproduce**
1. Start Discover Overlay Configuration, click on Voice
2. Click Place Window
3. Get error "python3.10 quit unexpectedly"

**Expected behavior**
A popup appearing to drag window to desired location

**Problematic behavior**
Crashes Discover

**Desktop (please complete the following information):**
 - OS: Fedora 38 Workstation
 - Wayland session
**Installation Method**
- Flatpak

**Comment by trigg** [comment]
Gnome on Wayland does not support this project and there is no reliable way to make this work on it. I'd advise not using Gnome or using X11 Gnome.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1141

**Comment by JustCryen** [comment]
Hi, there's a project named [activate-linux](https://github.com/MrGlockenspiel/activate-linux) which in fact makes the text visible on screen like the overlay would.
I have no idea what it uses to achieve this but well… it works.
It does disappear when opening overview but other than that it's working as intended :)

**Comment by trigg** [comment]
[I'm aware of the project](https://github.com/MrGlockenspiel/activate-linux/pull/149l)

Looking at [the source](https://github.com/MrGlockenspiel/activate-linux/blob/7699cd91ba4d53539d98f3beddf5464ef76e06c2/src/wayland/wayland.c#L336) it has no specific code paths for gnome wayland, so it appears to just make a window and trust to luck that it'll be visible at any given time.

**Comment by JustCryen** [comment]
Ahh, great that it's at least known about. That's what I was after.

I can't say much of anything else, I just wanted to make you aware of it but yeah, I didn't know you actually contributed there ;P

Btw, there's an extra letter in your "I'm aware of the project" link. Thanks for your work!


I'm in a process of developing a gnome extension that should be able to use overlays.
I'll try to get this working but it's not like I've ever written an extension or a program this scale… so it might be a while to get the prototype running.

**Comment by trigg** [comment]
> Btw, there's an extra letter in your "I'm aware of the project" link. 

Thanks for pointing that out, typos are my specialty!

> I'm in a process of developing a gnome extension that should be able to use overlays.

This sounds very interesting, I'll need to leave myself a note to look back in on it later. 

I'm hearing good things from the Bazzite crowd about using [this workaround](https://github.com/trigg/Discover/wiki/Special-use-cases#wayland-via-xwayland) to get it working on Gnome, but I have a long-seated dislike of Gnome as a desktop and can't bring myself to use it for any reasonable testing. 

> I didn't know you actually contributed there ;P

I'm good at sticking my nose into other peoples work.

**Comment by cprin21** [comment]
> I have a long-seated dislike of Gnome as a desktop and can't bring myself to use it for any reasonable testing.
I can respect it, I don't feel comfortable on a technical level personally but I'm sure you could have some sort of beta or a patch for the git version that others could test.

**Comment by JustCryen** [comment]
I can confirm that it actually works literally like the previously mentioned "activate-linux" project.
That means, it's visible over the top of other windows but it vanishes temporarily when in the system overview.
And I actually like that behavior.
I have not yet tested any other feature other than speech indicator so if any testing is needed, just let me know.

(Crazy thing that I was about to post that today anyway but you @cprin21 were faster by about 6 minutes) xP

**Comment by JustCryen** [comment]
Quick test I've conducted shows that everything works as expected.
Voice bubbles, text channels, notifications, all of it.
The Discover Overlay Configuration can be launched normally (without GDK_BACKEND=x11) and any changes still apply dynamically to the overlay.

The only thing that's currently not working is the "Place Window" feature in both, Voice and Text tabs.
Additionally, "Run overlay on startup" setting would require the GDK_BACKEND variable to be applied.

**Comment by JustCryen** [comment]
One more thing, this seems like a bug that is probably not related to the gnome wayland but to the project itself. Since I'm not entirely sure, I don't want to open a new issue for it.

When "Show Text Content", "Show Names" and "Highlight Self" options are enabled, voice bubbles don't show up on the overlay at all.
If one of the options get disabled, everything looks alright again. It only happens when displaying users vertically.

**Comment by trigg** [comment]
>  "Show Text Content", "Show Names" and "Highlight Self"

I see it now you've pointed it out. Test content hasn't got a [valid self_user](https://github.com/trigg/Discover/blob/14069fbd722156c3a3abce70e7a912941556d4ab/discover_overlay/voice_overlay.py#L527) so we're accidentally inserting dud data here.

Thanks for the heads up, that should be a quick fix.

**Comment by mavit** [comment]
Would you accept a patch that set `GDK_BACKEND=x11` automatically if an unsupported compositor was detected?

**Comment by trigg** [comment]
I am unsure how I feel about that.

Does it, under current Gnome, work with that change?

I had considered something similar recently but as I do zero testing using Gnome I couldn't guarantee it myself.

**Comment by mavit** [comment]
After one minute of testing it seems fine, but I'll come back when I've had an opportunity to test it more thoroughly.

**Comment by DodoLeDev** [comment]
There will be more solutions to make this overlay working on pure Wayland (and without the Layer Shell protocol extension):
- A new protocol implementation is in the works for making apps "always on top": [xdg-pip](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/132)
- The [XDG-session-management](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18), even if it still not belongs to the official wayland spec yet, has been merged in [KWin](https://invent.kde.org/plasma/kwin/-/merge_requests/7475) and [Mutter](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3825), allowing Discover to keep the window placement for the overlay (you can trick the compositor by using the session ID of the positioned window in settings when displaying the overlay. Compled with the ability to "lock" the window, this may work)

**Comment by trigg** [comment]
Some interesting ideas. I'd seen the latter but hadn't considered it could be (mis-)used in this way.
