### ISSUE TITLE
[Feature] Mumble support

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#3]
Would be pretty neat to have Mumble integration. Could even support positional audio visually perhaps? 
e.g. someone on the left of you in game appears on that side of the screen, someone ahead at the centre top etc...

**Comment by jasikpark** [comment]
It seems that mumble might have overlays?

- https://github.com/mumble-voip/mumble/pull/4628
- https://github.com/toby63/mumble/blob/usage/docs/user-guides/overlay_openGL.md

Though the current implementation seems to be OpenGL injection into games when you launch them...

**Comment by jasikpark** [comment]
Ahah!: https://wiki.mumble.info/wiki/Overlay

**Comment by Krzmbrzl** [comment]
Mumble does support Among Us. You just have to use the 1.4.0 development snapshot.
