### ISSUE TITLE
Inability to change monitor if all monitors have the same model name 

### ISSUE THREAD

**Issue by LeadSeason** [trigg/Discover#302]
**Steps to Reproduce**
1. Get 2 or more of the same monitor
2. Try to change monitor's
3. Wont change monitor. 

**Expected behavior**
Discover overlay would change monitors

**Desktop (please complete the following information):**
 - OS: arch
 - Wayland Compositor: swayfx

**Installation Method**
- discover-overlay-git v0.6.5.r0.g5414538-1

**Comment by trigg** [comment]
Unable to complete step 1. Looking into this now regardless

**Comment by trigg** [comment]
Latest commit now stores monitors by index, rather than name.

If monitor layout changes between runs it will change which monitor the overlay is displayed but it should now differentiate equally named monitors

**Comment by trigg** [comment]
Fixed
