### ISSUE TITLE
Allow basic chatting

### ISSUE THREAD

**Issue by Madis0** [trigg/Discover#309]
Voice chat can have a keybind set by the Discord app, but I haven't been able to find a way to chat with text. 
Can you add a hotkey and a textbox to the overlay?

**Comment by trigg** [comment]
No.

The way this overlay is designed does not allow for a text input, or mouse input.

it will require a complete rewrite from scratch and even then I don't believe this is doable. 

To top it off, I'm not even sure if the RPC websockets allow for text sending either
