### ISSUE TITLE
Suggestion: Clicking notification could show discord app

### ISSUE THREAD

**Issue by AlurienFlame** [trigg/Discover#310]
Something I find myself doing quite often is trying to click the notification to tab into discord and see the message in context. It would be nice if there was a setting to enable that functionality.

**Comment by trigg** [comment]
While I can see the appeal of this suggestion I don't believe it's something we can control.

For a start we have mouse input turned off to avoid a slew of issues that it causes, and in gamescope mode it will absolutely not receive input, even if we accept it.

Secondly Discord RPC has no command to present the window, and we can't be certain the window even exists at any given time as it may have been closed to the system tray.
