### ISSUE TITLE
Should Gracefully quit if user denies Discord permissions

### ISSUE THREAD

**Issue by RenzoAPM** [trigg/Discover#316]
**Steps to Reproduce**
1. Install
2. Authenticate Streamkit Overlay
3. Uninstall

**Expected behavior**
Discord overlay will no longer appear when joining a voice channel.

**Problematic behavior**
It still appears when joining a voice channel.
Also, if you add the step:
4. Deauthenticate Streamkit Overlay
Streamkit Overlay will continue to repeatedly ask for authentication every few seconds.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon

**Installation Method**
 - OS package manager

**Solution**
1. Open System Monitor or Terminal
2. End Discover_Overlay process

**Additional comment**
I am mainly creating this issue to help anyone having issues uninstalling Discover_Overlay. It would also be nice if the discover overlay process did not continue after it is uninstalled. Maybe there is a way it can check if the `~/Discover` folder exists. Maybe the steps to uninstall could be added to the `README.md`, even though it is simple.

**Comment by trigg** [comment]
As with everything else in linux-based systems, Uninstalling a program does not stop any running instances.

As you discovered, you could use a task manager to close the process, or close it out from the config window before uninstalling it. 

As for repeatedly asking for authentication, we probably could do with a system to not ask again if explicitly denied. It simply wasn't a needed feature before.

The major issue with checking ~/ files is that they will not be deleted on uninstall either

**Comment by RenzoAPM** [comment]
Thanks for the hasty reply. You mentioned the config window, but I'm not sure where to find this. I tried running the command `discover-overlay --configure` but the `discover-overlay` command is not recognized. Would you like me to create a separate issue? Feel free to close this one whenever you feel like it.

**Comment by RenzoAPM** [comment]
I figured it out. It's listed as a separate app (Discover Overlay Configuration) which can be found in my app menu. You may close this issue, or leave it open until you fix the repeating authentication requests for Streamkit Overlay. It's up to you. Thank you for your help.

**Comment by trigg** [comment]
I'll rebrand it, it still has purpose!

**Comment by trigg** [comment]
Fixed in latest commit.

Closes with an error log to explain why
