### ISSUE TITLE
unable to open configuration window

### ISSUE THREAD

**Issue by MNS26** [trigg/Discover#317]
**Steps to Reproduce**
1. clone from github
2. installl
3. open discover-overlay --configure

**Expected behavior**
it opening the configuration menu

**Problematic behavior**
when launching configuration to gives an error

**Desktop (please complete the following information):**
 - Operating System: Fedora Linux 39
 - KDE Plasma Version: 5.27.9
 - KDE Frameworks Version: 5.111.0
 - Qt Version: 5.15.11
 - Kernel Version: 6.5.11-300.fc39.x86_64 (64-bit)
 - Graphics Platform: X11
 - Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
 - Memory: 30.5 GiB of RAM
 - Graphics Processor: AMD Radeon RX 6700 XT
 - Manufacturer: Micro-Star International Co., Ltd.
 - Product Name: MS-7D77
 - System Version: 1.0

**Installation Method**
 - git clone & pip

**Additional context**
the error 
```py
❯ discover-overlay --configure
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.6.9
INFO - discover_overlay.autostart - Autostart info : desktop /home/noah/.local/share/applications/discover_overlay.desktop auto /home/noah/.config/autostart/discover_overlay.desktop
INFO - discover_overlay.autostart - Autostart info : desktop /home/noah/.local/share/applications/discover_overlay_configure.desktop auto None
ERROR - discover_overlay.discover_overlay - Argument 1 does not allow None as a value
ERROR - discover_overlay.discover_overlay - Traceback (most recent call last):
  File "/home/noah/.local/lib/python3.12/site-packages/discover_overlay/discover_overlay.py", line 520, in entrypoint
    settings = MainSettingsWindow(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/noah/.local/lib/python3.12/site-packages/discover_overlay/settings_window.py", line 151, in __init__
    self.read_config()
  File "/home/noah/.local/lib/python3.12/site-packages/discover_overlay/settings_window.py", line 307, in read_config
    self.widget['voice_title_font'].set_font(font)
TypeError: Argument 1 does not allow None as a value

/mnt/data/Projects/Discover-overlay master ❯    
```

**Comment by MNS26** [comment]
ok found the problem... the config.ini was fucked

**Comment by MNS26** [comment]
this is the ini that broke it (had to add .txt so it would upload)
[config.ini](https://github.com/trigg/Discover/files/13363794/config.ini.txt)

**Comment by MNS26** [comment]
hmm manually wnet throuh and commented 1 by 1 and worked after commenting the line `title_font = Sans 14`

**Comment by trigg** [comment]
Thanks for the report! This one appears to resurface every now and then and I'm not certain why.
