### ISSUE TITLE
Feature Request: automatically set positioning to floating on cinnamon

### ISSUE THREAD

**Issue by binarynoise** [trigg/Discover#322]
To prevent #299 and #98 in future, would it be possible to detect if the Discover Overlay is run on cinnamon to automatically switch to floating?

**Comment by trigg** [comment]
This might be a potential fix. It would need a sensible way to find out if the user is on cinnamon...

 Could you please provide the output of `env | grep XDG_SESSION_DESKTOP`
 I'm hoping that will be enough to work off of

**Comment by binarynoise** [comment]
```shell
$ env | grep XDG_SESSION_DESKTOP
XDG_SESSION_DESKTOP=cinnamon
```

**Comment by trigg** [comment]
Ah I hoped so! 

Yep I'll look into this then

**Comment by trigg** [comment]
It's not the prettiest, but it will ignore 'edge' choice in cinnamon desktop now.

To really call this fixed we probably need a way to explain this to new users

**Comment by binarynoise** [comment]
Next step could be disabling the anchored radio box in the settings UI.
I don't program in python, otherwise I'd help you with that...
Thanks for the workaround though.

**Comment by trigg** [comment]
That's done too. I'll close for now as this shouldn't cause further issue.
