### ISSUE TITLE
possible memory leak, ram usage rose to 11.4GB

### ISSUE THREAD

**Issue by Spiderfffun** [trigg/Discover#323]
**Steps to Reproduce**
not sure
i was installing rocm drivers and invokeai in the background, that might have caused it
note that i wasnt in a call when it happened

**Expected behavior**
ram not to rise to 11gb

**Problematic behavior**
ram rose to 11gb

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3

**Installation Method**
 - flatpak

**Comment by trigg** [comment]
How are you measuring Ram usage?

**Comment by Spiderfffun** [comment]
> How are you measuring Ram usage?

Gnome system monitor on Linux Mint. The applet also showed my ram and swap usage rise from like 50% ram 0% swap to 90% ram 90% swap.

**Comment by trigg** [comment]
So you're measuring entire system ram usage? It would be a better plan to do per-process usage to see what is happening.

In a terminal run `top` and press `Shift-m` to sort by memory usage.

![2024-03-17_16:43:46](https://github.com/trigg/Discover/assets/535772/82df82de-8354-444f-bed8-a99caa226208)

In my case it is firefox, steam and discord.

**Comment by Spiderfffun** [comment]
> So you're measuring entire system ram usage? It would be a better plan to do per-process usage to see what is happening.
> 
> In a terminal run `top` and press `Shift-m` to sort by memory usage.
> 
> ![2024-03-17_16:43:46](https://private-user-images.githubusercontent.com/535772/313489790-82df82de-8354-444f-bed8-a99caa226208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTg4OTAsIm5iZiI6MTcxMDc1ODU5MCwicGF0aCI6Ii81MzU3NzIvMzEzNDg5NzkwLTgyZGY4MmRlLTgzNTQtNDQ0Zi1iZWQ4LWE5OWNhYTIyNjIwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDQzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWEzYjNjMjkxMDY5NjkwNzViYWM1NmMzOTI0MjdlZGYwMjc3ODZkOWI2MGY5ZjZhOThlZDA2ZmZjODk0MTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HWFwg8uyvACMr6JQme-7nGRIr5SvEf2o4O1bT06eGaA)
> 
> In my case it is firefox, steam and discord.

It was the overlay in system monitor having 11gb, the entire system rose to like 20gb including other programs. This also might have been due to a file system corruption, it all became read only, somewhere around that time.

**Comment by RodoMa92** [comment]
Same thing for me on bazzite, it was hard locking my device and stealing 95% of system memory and one single core in the background while on desktop on Deck. Had to kill it to get back my system (I realized that something was wrong when my mouse was barely moving and after opening glances I immediately saw discover-overlay as the root cause of it).

**Comment by trigg** [comment]
@Spiderfffun Are you KDE too? Your usage of gnome system monitor implies otherwise but you missed out mentioning your DE

**Comment by trigg** [comment]
Ok, next question: How are you installing discord?

**Comment by RodoMa92** [comment]
> Ok, next question: How are you installing discord?

Just using Vesktop flatpak client on my end.

**Comment by trigg** [comment]
I've put out a bugfix which, for your case as least, should fix this.

I'm unsure if your issue is the same one @Spiderfffun is experiencing

**Comment by RodoMa92** [comment]
> I've put out a bugfix which, for your case as least, should fix this.
> 
> I'm unsure if your issue is the same one @Spiderfffun is experiencing

Thanks for the quick turnaround time! As soon as I do get 0.7.1 I'll definitely report back with the results. Thanks again for your time :)

**Comment by Spiderfffun** [comment]
> @Spiderfffun Are you KDE too? Your usage of gnome system monitor implies otherwise but you missed out mentioning your DE

No, Cinnamon.
I also use vesktop, if that makes a difference.

**Comment by Spiderfffun** [comment]
> Any chance of some reproduction steps? What desktop environment? Potentially even worth looking at hardware similarities.

![image](https://github.com/trigg/Discover/assets/85702798/9c4e839a-e04f-41e4-b6a3-c091d0ca744d)
here's my fastfetch for hardware

**Comment by trigg** [comment]
Thanks. It absolutely looks like vesktop is the link here.

As above then, the newest update should fix it.
