### ISSUE TITLE
Mute or Unmute on Overlay Press 

### ISSUE THREAD

**Issue by SetoNaikai** [trigg/Discover#326]
When using the overlay muting quickly via pressing the overlay would be helpful. Unmuting by pressing it again would be ideal.

**Comment by trigg** [comment]
Interesting idea, for the most part we don't accept input, allowing it to pass through behind the overlay.

But I suspect we might be able to get this in and for it work for handful of Desktop environments

**Comment by SetoNaikai** [comment]
Would it be possible to look into it for the steam deck as well? I saw that
there was the terminal option for mute or unmute. Would be great if a
button press could do that.

**Comment by trigg** [comment]
The last time I checked overlays on gamescope/gamemode aren't given any user input at all.

It would probably be necessary to write a plugin for something like decky loader. That could be done marginally quickly but I honestly don't know how to code for that

**Comment by SetoNaikai** [comment]
Gotcha, thanks for giving it so much thought.

I found a workaround to setup a shortcut in discord to mute which works
well but the options of what buttons to map using the steam deck desktop
configuration sometimes doesn't work.

**Comment by iiscosd3** [comment]
> allowing it to pass through behind the overlay.

You always can intercept if a keyboard keys combination is being invoked, for example shift click, shift right mouse button click etc. Its all simple.

**Comment by trigg** [comment]
> You always can intercept ...
We certainly cannot do that, not without some really funky stuff like snooping keyboard events that aren't sent to us.
