### ISSUE TITLE
Support for vesktop

### ISSUE THREAD

**Issue by anthr76** [trigg/Discover#329]
Hello! I make great use of this project but recently swapped over to vesktop from the native Discord client and I noticed the discover overlay no longer works. Is it possible to support vesktop?

**Comment by trigg** [comment]
This is included in #312 

I would *love* to, but none of the modded clients have the extended RPC required to get voice data out of the client.

https://github.com/OpenAsar/arrpc/issues/18

I'll be closing this one in favour of the existing issue and adding it to the list

**Comment by anthr76** [comment]
Thank you!
