### ISSUE TITLE
pipewire/pulseaudio integration issue

### ISSUE THREAD

**Issue by ilobilo** [trigg/Discover#330]
### **Steps to Reproduce**
1. undeafen and unmute while in a call
2. deafen by muting system audio output
3. then mute by muting system mic
4. undeafen by unmuting system audio output
5. discord microphone gets unmuted but system mic is still off, so they are out of sync

### **Expected behavior**
either discord should stay muted or system mic should get unmuted

### **Problematic behavior**
^

### **Desktop (please complete the following information):**
 - Operating System / Distrobution : Ubuntu 23.10
 - Desktop Environment : KDE Plasma 5.27.8

### **Installation Method**
 - flatpak

### **Discord client information**
 - Install method : deb
 - Version : Stable 284422 (923f1ee) 0.0.49 x64

### **Additional context**
none

**Comment by ilobilo** [comment]
btw system tray icon is very low quality. also, can i change the name to remove `-` and capitalise the words?
![image](https://github.com/trigg/Discover/assets/68286835/22eeb5c6-5c65-4f29-8ce2-c9784f1c2fd1)

**Comment by trigg** [comment]
> ... also, can i change the name to remove ...

What system tray shows a name? I've never seen this before

**Comment by trigg** [comment]
Thank you, I never considered this particular set of steps as it is one I can't see happening with my setup. I apologise.

I'll look into icon next

**Comment by trigg** [comment]
If I'm honest I think you're the only flatpak user who has a systray icon as they've been known to not work...

**Comment by trigg** [comment]
A solid point. I can't remember if there's a way to get discord to report it back but I'll look at it!
