### ISSUE TITLE
Display stream/screenshare viewers 

### ISSUE THREAD

**Issue by iiscosd3** [trigg/Discover#332]

**Comment by iiscosd3** [comment]
Could've been implemented by inventing a new icon? As in an eye or something, i am not sure.

**Comment by trigg** [comment]
The last time I checked we don't have access to who is watching us. I'll read through the API again

**Comment by iiscosd3** [comment]
Could you post the api link itself as well?

**Comment by trigg** [comment]
https://discord.com/developers/docs/topics/rpc

We use this RPC

**Comment by trigg** [comment]
I strongly suspect arRPC would be a great answer to this problem.

As an open project it would be possible to add extra subscriptions for events like watching state.
