### ISSUE TITLE
Failed to start overlay in wayland  EndeavourOS

### ISSUE THREAD

**Issue by Tune45** [trigg/Discover#335]
System 
ENdeavourOS 
KDE 6.0.5
KDE frameworks 6.2.0
kernal 6.9.1
Graphic platform wayland

detail error code in screenshot in attach file
![Screenshot_20240527_161856](https://github.com/trigg/Discover/assets/138557979/29a50c59-ffbd-4db8-aa7c-93b98919774d)

**Comment by trigg** [comment]
So it's a complaint you don't have gtk layer shell installed, which is a requirement if you're using wayland

Is this installed via AUR, flatpak or from source?

**Comment by trigg** [comment]
https://archlinux.org/packages/extra/x86_64/gtk-layer-shell/

**Comment by trigg** [comment]
Yeah, in that case just `sudo pacman -S gtk-layer-shell`

It's an optional dependency that allows function on wayland desktops

**Comment by trigg** [comment]
Glad to help!
