### ISSUE TITLE
Fails To Autostart (Correctly) On Fedora 40 (KDE Plasma Spin)

### ISSUE THREAD

**Issue by cprin21** [trigg/Discover#342]
### **Steps to Reproduce**
1. Select Discover Overlay to auto start whether by pointing to it as an application or pointing to a login-script which runs it
2. Reboot
### **Expected behavior**
Discover Overlay showing
### **Problematic behavior**
Discover Overlay technically does start but to no effect.
Starting normally by launching it works.

### **Desktop (please complete the following information):**
 - Operating System / Distrobution : Fedora 40
 - Desktop Environment : KDE Plasma

### **Installation Method**
-Flatpak AND the (outdated) COPR repo which is still on 0.72

### **Discord client information**
 - Install method : rpmfusion-nonfree repo
 - Version : stable 315285 (c86f7ed)

**Comment by trigg** [comment]
Flatpak most certainly won't autostart, and I'm not in control of the COPR repo.

I'd advise, for now, putting the applications into KDE's autostart.

**Comment by cprin21** [comment]
Unfortunately that's exactly what I've been doing. Works just fine manually running the app, though, so I've been starting it manually.

**Comment by trigg** [comment]
Note to self : Potentially linked to #348
