### ISSUE TITLE
Overlay opens on the wrong screen (Two monitors the same model)

### ISSUE THREAD

**Issue by DarkArc** [trigg/Discover#343]
### **Steps to Reproduce**
1. Setup the overlay to open on the secondary monitor

### **Expected behavior**
The overlay opens on the secondary monitor

### **Problematic behavior**
The overlay opens on the primary monitor

### **Desktop (please complete the following information):**
Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.12-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 61.9 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: ASUS

### **Installation Method**
flatpak (io.github.trigg.discover_overlay 0.7.4)

### **Discord client information**
 - Install method : flatpak (com.discordapp.Discord)
 - Version : 0.0.62

### **Additional context**
 
I _think_ the issue is that if you look at my overlay location settings, both monitors show up with the same name. So even when I fix it to pick the secondary monitor, it finds the primary monitor first because they have the same model number.

I can fix it by changing the entry selected in the drop down.

**Comment by trigg** [comment]
This is fixed in latest, but it looks like Flatpak fell behind in one stable version. I'll try to get a release out very soon

**Comment by trigg** [comment]
(for the sake of completeness of my documentation)

Linked to #334

**Comment by DarkArc** [comment]
Thanks, can confirm this is now fixed.
