### ISSUE TITLE
Self Highlight option no longer displays yourself when set to Speakers Only

### ISSUE THREAD

**Issue by skinnay-dev** [trigg/Discover#345]
### **Steps to Reproduce**
1. Open Discover Overlay Configure
2. Click on the Voice - Advanced tab
3. Select "Display Speakers Only" and "Highlight Self"
4. Notice that your username/avatar is not displayed unless speaking

### **Expected behavior**
In a previous version of discover, my own user would always be shown regardless of whether I was speaking. This was very useful to track my muted state.

### **Problematic behavior**
The "Highlight Self" option is not keeping me always displayed. I have looked for other configuration that would result in the same behavior with no luck.

### **Desktop (please complete the following information):**
 - Operating System / Distrobution : Arch
 - Desktop Environment : i3wm

### **Installation Method**
 AUR discover-overlay-git

### **Discord client information**
 - Install method : pacman
 - Version : 0.0.63

**Comment by trigg** [comment]
Fixed in latest commit

**Comment by trigg** [comment]
Thank you for your report :D
