### ISSUE TITLE
Fails to start with "SyntaxError: f-string: unmatched '('"

### ISSUE THREAD

**Issue by BrunchPunk** [trigg/Discover#346]
### **Steps to Reproduce**
1. Installed Discover Overlay via flatpak
2. Attempted to launch it and the configuration UI via Applications shortcut, but nothing appeared
3. Attempted to launch via the OS application store, but nothing appeared
4. Attempted to start by flatpak on the command line and received the following error 

`flatpak run io.github.trigg.discover_overlay
Traceback (most recent call last):
  File "/app/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/app/lib/python3.11/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/app/lib/python3.11/site-packages/discover_overlay/discover_overlay.py", line 101
    print(f"{_("Usage")}: discover-overlay [OPTIONS]... ")
                ^^^^^
SyntaxError: f-string: unmatched '('`

### **Expected behavior**
Discover Overly, or its configuration UI, launches

### **Problematic behavior**
Nothing launches and there is no indication of a failure unless started from the command line

### **Desktop (please complete the following information):**
 - Operating System / Distribution : Pop_OS
 - Desktop Environment : Gnome/Wayland

### **Installation Method**
 - flatpak

### **Discord client information**
 - Install method : flatpak
 - Version : stable 318966 (48a348b) Host 0.0.64 x64 Build Override: N/A Linux 64-bit (6.9.3-76060903-generic)

### **Additional context**
I had been using Discover Overlay successfully with X11 but recently switched to Walyand. Afterwards, the behavior described above began to occur. 

I have attempted to remove and reinstall the flatpak, but this did not address this. 

I attempted to install with pip as described in the readme and was able to after installing `libgtk-layer-shell-dev`. However, the behavior was Identical. I was able to run the command `discover_overlay` and `discover_overlay -c` but they resulted in the same error message.

**Comment by BrunchPunk** [comment]
Tried again today after the update and it failed to reproduce! I'm getting a different error now, but this one's clearer and points to an incompatibility with this compositor. Sorry to bother you!

**Comment by trigg** [comment]
Not a bother! Sorry I meant to reply between seeing this and putting out a bugfix but got distracted.

I've heard some good results for running in [Gnome via XWayland](https://github.com/trigg/Discover/wiki/Special-use-cases#wayland-via-xwayland) but I'm unable to officially support it as there's no guarantee it won't break in later versions of Gnome.

In case of flatpak possibly `GDK_BACKEND=x11 flatpak run io.github.trigg.discover_overlay`
