### ISSUE TITLE
Overlay left/right window anchor position isn't right on high resolution monitors

### ISSUE THREAD

**Issue by DarkArc** [trigg/Discover#347]
### **Steps to Reproduce**
Set the overlay to be anchored to the right edge of the screen.

### **Expected behavior**
It only makes it part way to the right edge of the screen.

### **Problematic behavior**
It's on the right edge of the screen.

### **Desktop (please complete the following information):**
Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.4-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 61.9 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XTX
Manufacturer: ASUS

### **Installation Method**
flatpak

### **Additional context**
It seems like the overlay isn't actually grabbing the screen resolution properly. Curiously, the vertical positioning (top, middle, bottom) is spot on.

I have 4k monitors, and it only gets vaguely in the right spot if I set my display scale to 2x.

### **Workaround**
I'll add that I  have a workaround, which is to anchor to the left, then push the overlay into the right position using the vertical and horizontal edge padding.

This doesn't work if you want to "Show Names" (but I don't particularly need that feature).

i.e., I'm reasonably satisfied with the status-quo but I figured I'd report this in case you want to try and fix it.

**Comment by trigg** [comment]
Most certainly the same issue as #338

**Comment by trigg** [comment]
This is an issue with render-scale which needs some looking into. Essentially, any non-integer scale causes the screen-size logic to give incorrect information

**Comment by trigg** [comment]
Closing this in favour of #338
