### ISSUE TITLE
Can't enable some Core settings

### ISSUE THREAD

**Issue by Droppisalt** [trigg/Discover#348]
### **Steps to Reproduce**
1. Run discover-overlay -c
2. Go to Core
3. Select either "Run Overlay on Startup" or "Run Configuration on Startup"
4. Look at error in terminal
5. Closing and reopening the configuration screen makes both options from step 3 un-checked.

### **Desktop (please complete the following information):**
 - Operating System / Distrobution : Fedora
 - Desktop Environment : KDE

### **Installation Method**
 - `python3 -m pipx install discover-overlay`

### **Discord client information**
 - Install method : dnf
 - Version : 
```
stable 320157 (3fce75b) Host 0.0.64 x64 Build Override: N/A Linux 64-bit (6.8.12-200.fsync.fc39.x86_64)
Vencord eaca14b (Standalone)
Electron 30.2.0
Chromium 124.0.6367.243
```

**Comment by trigg** [comment]
I'm currently unable to reproduce this, I'll look into a Fedora install soon
