### ISSUE TITLE
missing dependency: requests

### ISSUE THREAD

**Issue by Findus23** [trigg/Discover#35]
I tried installing this in a fresh virtualenv, but noticed that requests was used, but not specified in the requirements:

https://github.com/trigg/Discover/blob/62aa3a7da69fa5cb17918debf3ff7090c48b0da6/discover_overlay/discover_overlay.py#L23

https://github.com/trigg/Discover/blob/62aa3a7da69fa5cb17918debf3ff7090c48b0da6/setup.py#L20-L24

Apart from that everything seems to be working fine on Debian Testing KDE

**Comment by trigg** [comment]
Very odd that it survives the build system without it. Thank you!
