### ISSUE TITLE
doesn't work on vesktop

### ISSUE THREAD

**Issue by fe2-Nyxar** [trigg/Discover#350]
it's not a bug, I just installed Vesktop and tried to use discover-overlay, and it doesn't work, I'm just asking if we can get a compatible version with Vesktop.

### **Desktop (please complete the following information):**
 - Operating System / Distrobution: Nixos
 - Desktop Environment: Plasma 6

### **Installation Method**
 - nixpkgs

**Comment by trigg** [comment]
Unfortunately a duplicate of #312 . Closing in favour of that one
