### ISSUE TITLE
Gnome 45 runtime is EoL

### ISSUE THREAD

**Issue by wilsonephillips** [trigg/Discover#353]
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.trigg.discover_overlay

**Comment by wilsonephillips** [comment]
Thank you sir.

**Comment by trigg** [comment]
Bumped the flatpak dependencies

**Comment by wilsonephillips** [comment]
Thank you very much.

Wilson Phillips
145 Bradford Dr Lot 12
Vicksburg, MS 39180
(601) 642-8383

Guarantee does not cover shark bite, bear attack or children under 5

________________________________
