### ISSUE TITLE
Images for Readme

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#4]
Let's make the readme more useful. I'll start.

![Screenshot from 2020-09-23 16-28-44](https://user-images.githubusercontent.com/964775/94065879-9c4e4480-fde3-11ea-9b8a-4688fd02ca17.png)

Might also be worth a demo video to show off features.

**Comment by i-need-to-tell-you-something** [comment]
Great idea. It adds so much already to the readme. This above exact screenshot would imo be even better if the muted person's avatar would be much more plain or clear. Something very recognizable or simple. Because for me it took several sightings of this screenshot and actually trying out this software for myself before I realized that Trigg is muted in this example. I assumed the red parts part of their avatar.

**Comment by gjkf** [comment]
![Screenshot from 2020-10-02 12:11:41](https://user-images.githubusercontent.com/8215189/94913119-fd8fab00-04a8-11eb-8387-1df1adda13e2.png)
Text chat settings

![Screenshot from 2020-10-02 12:11:56](https://user-images.githubusercontent.com/8215189/94913140-04b6b900-04a9-11eb-8bf8-0ef1b39ecb97.png)
Voice chat Settings

**Comment by MoralCode** [comment]
i posted an image of some changes i made to the text settings screen in #88.
here are the other screens just for consistency:

![Screenshot_20201018_202329](https://user-images.githubusercontent.com/17362949/96399677-ce08c000-1183-11eb-80ee-29580bfcc606.png)
![Screenshot_20201018_205241](https://user-images.githubusercontent.com/17362949/96399709-e082f980-1183-11eb-87ea-6119ff5f0767.png)

**Comment by trigg** [comment]
![Screenshot_2022-01-15_00-24-25](https://user-images.githubusercontent.com/535772/149630830-750f8af6-e935-44a6-ad1c-da1d204ee107.png)

**Comment by trigg** [comment]
just adding new content 

![94065879-9c4e4480-fde3-11ea-9b8a-4688fd02ca17](https://github.com/trigg/Discover/assets/535772/32c40af6-0700-4899-aaa2-46268e65213d)

**Comment by trigg** [comment]
going for something larger
![Screenshot_20230928_150901](https://github.com/trigg/Discover/assets/535772/8f661195-2517-4a27-b420-8370fff57793)
