### ISSUE TITLE
Discord freezes when I start discover 

### ISSUE THREAD

**Issue by ThatOneCalculator** [trigg/Discover#41]
Just as the title says. Happens with the latest version of Discord.

**Comment by trigg** [comment]
every time? What OS?

**Comment by ThatOneCalculator** [comment]
Every single time, both with and without betterdiscord. Pop!_OS 20.04 LTS with XanMod 5.8

**Comment by midget3111** [comment]
Do you have a log you can post from running Discord and Discover via the command line?

**Comment by ThatOneCalculator** [comment]
Nothing interesting came from the discover command line, but when running discord from the command line, as soon as I ran discover and it froze this appeared:

```
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(node:338924) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
(node:338924) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
```

**Comment by midget3111** [comment]
Interesting. Out of interest, how many guilds or servers are you in?

**Comment by UltraBlackLinux** [comment]
Same here:
Discord Stable
Manjaro KDE (linux)
34 Servers

Everytime I do anything, discord freezes for like 3-5 seconds.

**Comment by trigg** [comment]
Despite the seeming similarity in error messages, the deprecation has nothing to do with discover. I just didn't name my logger so "root" was the default. The bug is VERY likely to be that on start discover tries to find what voice room you're in and requests info for every voice room you have access to in the hope you're in one. This might overload discord if you have enough rooms

**Comment by UltraBlackLinux** [comment]
So Propably add a delay, like 2 seconds?

**Comment by ozcodex** [comment]
I have to remove the system tray (gnome appindicator) and then discord works fine, but now i cannot use Discover -_-
please @trigg add a non-system tray interface. thks

**Comment by trigg** [comment]
Run `discover-overlay --configure` when it's already running to get the configuration window.

**Comment by trigg** [comment]
Has anyone with this issue attempted a recent version?
