### ISSUE TITLE
Make usernames show below/above avatar

### ISSUE THREAD

**Issue by rolypolypanda** [trigg/Discover#42]
Right now, the usernames only show beside the avatars.

Can the usernames be displayed below or above the avatars?

**Comment by midget3111** [comment]
Any reason for this? 
Seems like it would take up quite a bit of space and I'm trying to figure out what the use case is :D

**Comment by trigg** [comment]
While possible, how would you envision names longer than the icon being displayed?

Just so I have an idea of what the expectations are
