### ISSUE TITLE
[Feature] VR support [Needs testing] 

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#44]
With The Vive and Index now supporting Linux, I wonder how the overlay would interact with them. This needs testing.

**Comment by trigg** [comment]
If supplied with equipment I could attempt to work on this feature.

Most likely scenarios:
1) Most likely :  It appears with no difference in position in both eyes, feeling like it's the closest thing to you in the scene
2) Fairly likely : It doesn't appear as rendering is done around X or Wayland and OS rendering never touches it
3) Not likely : It sets you personally on fire

**Comment by midget3111** [comment]
closing for now.
