### ISSUE TITLE
"Edge Padding" for voice overlay only affects vertical padding

### ISSUE THREAD

**Issue by GregTheMadMonk** [trigg/Discover#46]
This way, for example, changing **Edge padding** when overlay is vertically centered does practically nothing. It also seems unintuitive. Should edge padding affect both vertical/horizontal paddings or maybe it should be split into two separate options?

**Comment by trigg** [comment]
Although it's not clear by the label it is only intended to pad vertically for those of us who don't want it to hide system tray, menu icons or other needed desktop gui features.

The current answer to horizontal padding was to use floating windows, but I can see why some might not consider that good enough.

Is horizontal padding a feature you would use?

**Comment by GregTheMadMonk** [comment]
Yeah, I would love to be able to set horizontal padding. Having avatar literally touch right border of the screen feels... wrong? :)

Also, some people might have their panel on the right/left side of the screen, and for them it might be very important to also have horizontal padding.

**Comment by midget3111** [comment]
Have you tried the floating window positioning on the latest?

**Comment by GregTheMadMonk** [comment]
Yeah, it achieves what I propose, but feels more like a workaround. At the end of the day, if floating positioning is the way to do padding, why even have this option in the first place?

It would make sense (to me, at least) to have either both X/Y padding option or none.

**Comment by GregTheMadMonk** [comment]
Thanks! :+1:
