### ISSUE TITLE
Pop up style doesn't do anything

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#48]
After setting up a text channel - floating, enabled etc, it works as expected. 

However, When "Popup Style" is ticked, no text is shown even when messages are received.

Using Manjaro gnome

**Comment by trigg** [comment]
Messages more than 30 seconds old will not show up. To this end make sure your system clock is correctly set. The easiest way to do this is to use NTP

**Comment by midget3111** [comment]
Ta, all working now
