### ISSUE TITLE
Cannot debug the project anymore with VS Code

### ISSUE THREAD

**Issue by luni3359** [trigg/Discover#51]
I had to copy the ``__main__.py`` file from ``which discover-overlay`` over to the project to be able to run it with the debugger.

Here's my ``launch.json`` file
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "discover_overlay"
        }
    ]
}
```

**Comment by trigg** [comment]
Good idea! I had switched to running pip install & then the executable and debugging from command line.

**Comment by luni3359** [comment]
I thought you were going to add it because it's still erroring out while debugging.

**Comment by trigg** [comment]
__main__.py is created by setup.py at compile time. I'm not sure how you'd go about this and had assumed you were content with your own fix, my apologies on the assumption

**Comment by luni3359** [comment]
I don't mind personally, I just think other people might run into the same issue.

**Comment by trigg** [comment]
Short of writing it into the wiki a closed bug report is some documentation at least

**Comment by luni3359** [comment]
I put it in ``README.md`` on PR #99 because I couldn't figure out how to change the wiki. Not exactly right, so move it over if you want.

**Comment by trigg** [comment]
https://github.com/trigg/Discover/wiki/Debugging

Thank you for contributing too :D
