### ISSUE TITLE
[Feature] Grouped Server List Text

### ISSUE THREAD

**Issue by josh4789** [trigg/Discover#53]
Would it be possible to group the server list into different selections on the menu like one for server than one for the text channels within that server you have selected. I see that it kind of has them grouped anyway on the list but ive got quite a few servers and some have many text channels so scrolling through the entire list takes a long time.

**Comment by MoralCode** [comment]
I had a similar experience when perusing text channels and have started working on adding this feature. i'll commit and push my progress so far so others can contribute to this if desired
