### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by Kaito4Kid** [trigg/Discover#56]
Hello,
I can't figure out how to configure the settings.
Could someone explain that to me? 
Thank you!

**Comment by trigg** [comment]
![image](https://user-images.githubusercontent.com/535772/94841323-c326ff00-0411-11eb-8f72-149a353f98f9.png)
Hello! 
there should be a system tray/app indicator with the above image. If there is then right click it to get to settings. If not, then that is our issue.

Let us know which :D

**Comment by m4nnerheim** [comment]
Can confirm, I have no tray icon. I'm running default gnome DE that comes with the latest and greatest Pop OS. Any other information I can provide?

**Comment by midget3111** [comment]
Hey, I used this Gnome extension to get it to display :) 
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by m4nnerheim** [comment]
> Hey, I used this Gnome extension to get it to display :)
> https://extensions.gnome.org/extension/615/appindicator-support/

Ah I unfortunately can't load the extension. I keep getting "Error loading extension" even with manual installation.

**Comment by Kaito4Kid** [comment]
Hello! I DO have that app indicator, but when i click it nothing happens.

**Comment by MurdoMaclachlan** [comment]
This fix appears to have stopped the icon from showing correctly in my taskbar:
![image](https://user-images.githubusercontent.com/47920497/94918886-5fe9ab00-04ab-11eb-8825-1df129a2c4f4.png)
All functionality works the same; I can open settings, etc., but the icon is not showing.

I'm getting the error `INFO:root:Falling back to Systray : Namespace AppIndicator3 not available`, so I added some debug print statements to pin down where it was, and it seems to happen upon reaching `gi.require_version('AppIndicator3', '0.1')`, line 54 in discover_overlay.py

**Comment by MurdoMaclachlan** [comment]
> Is there by any chance a way to start it through terminal?

Try just entering "discover-overlay" in a terminal. That's how I've been running it.
