### ISSUE TITLE
Include (optionally) Images in text channels

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#57]
currently all images are shown as '--attachment--'. Optionally allow users to see the image sent

**Comment by gjkf** [comment]
I'd also add the ability to show emojies. Even custom ones if possible (they are just images after all, so should be pretty similar)

**Comment by trigg** [comment]
Emoji will show if you have them installed as a system font

I'm told in debian it is
`sudo apt install fonts-emojione`
