### ISSUE TITLE
Latest version crashes when connects to Discord

### ISSUE THREAD

**Issue by gjkf** [trigg/Discover#58]
I launched the latest (pull from Github) from the command line since it didn't seem to work. The following is the output
```
INFO:root:Autostart info : desktop /home/cossu/.local/share/applications/discover_overlay.desktop auto None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 741761057802158081
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:ID is 350229604365107211
INFO:root:Logged in as gjkf
INFO:root:Changing text room: 741761057802158081
Traceback (most recent call last):
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 399, in do_read
    self.on_message(msg)
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 266, in on_message
    self.add_text(message)
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 89, in add_text
    message["timestamp"], "%Y-%m-%dT%H:%M:%S.%f%z")
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-09-23T22:11:44.545Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```
After that, no matter what I do, the application won't respond.

EDIT: since in the settings window for the chat there was no text channel available to be selected, I modified the config in `~/.config/discover_overlay/config.ini` to another text channel and restarted the application. It correctly loaded all the text channels but at the end, the same error appeared. When I started again `discover_overlay` while I was already in a voice room, it no longer loaded the text channels.

**Comment by midget3111** [comment]
Hey, what OS / window manager are you using? 
Has the overlay worked previously for you? 
I'm also wondering whether you've enabled the pop up messages feature in text settings?

**Comment by gjkf** [comment]
Using Ubuntu 18.04 with Budgie (GNOME based) as DE.
Yes, the overlay has worked previously, after some tweaks due to how `pip` and `python` installed dependencies. Today I wanted to update it and try and contribute to this project in some way.
The `popup_style` option in the config is turned off (`0` in the file).

**Comment by midget3111** [comment]
Okay, ta. We'll look into it and get back to you.

**Comment by gjkf** [comment]
In case you need any more information/testing, let me know and I will be more than happy to give them.

**Comment by trigg** [comment]
Just a confirmation, it appears to be unable to decode the time being sent by server. I'll have a chance later today to fix this.

**Comment by trigg** [comment]
So interestingly the exact same variables do not cause a crash on my setup. It appears to be the micro-time that's causing the issue, but we won't know until you test the next commit (any minute now)

**Comment by gjkf** [comment]
Here is the full output:
```INFO:root:Autostart info : desktop /home/cossu/.local/share/applications/discover_overlay.desktop auto None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 625131638887546890
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:ID is 350229604365107211
INFO:root:Logged in as gjkf
INFO:root:Changing text room: 625131638887546890
2020-09-30T17:12:19Z
Traceback (most recent call last):
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 405, in do_read
    self.on_message(msg)
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 272, in on_message
    self.add_text(message)
  File "/home/cossu/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 95, in add_text
    time_input, "%Y-%m-%dT%H:%M:%S%z")
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-09-30T17:12:19Z' does not match format '%Y-%m-%dT%H:%M:%S%z'```
Each time I launch discover while being in a voice chat, no text chats are loaded too.

**Comment by trigg** [comment]
Are you able to open a terminal and run `python -i`

Rather than back and for on commits, let's use interactive python

```
import time
time.strptime("2020-09-30T17:12:19Z")
```
and 
```
import time
time.strptime("2020-09-30T17:12:19+00:00")
```

Thanks again for feedback

**Comment by gjkf** [comment]
Here you go

```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.strptime("2020-09-30T17:12:19Z")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-09-30T17:12:19Z' does not match format '%a %b %d %H:%M:%S %Y'

>>> time.strptime("2020-09-30T17:12:19+00:00")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-09-30T17:12:19+00:00' does not match format '%a %b %d %H:%M:%S %Y'
```

**Comment by trigg** [comment]
And could you once more for 
```
time.strptime("2020-09-30T17:12:19+00:00", "%Y-%m-%dT%H:%M:%S%z")
```

**Comment by gjkf** [comment]
```>>> time.strptime("2020-09-30T17:12:19+00:00", "%Y-%m-%dT%H:%M:%S%z")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-09-30T17:12:19+00:00' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

Is it me or this is not intended behaviour?

**Comment by trigg** [comment]
I'm thoroughly confused as to why it's not matching format. 

This was my only lead, I'll be back in 40 mins to get back to this

https://stackoverflow.com/questions/53291250/python-3-6-datetime-strptime-returns-error-while-python-3-7-works-well

**Comment by gjkf** [comment]
In the mean time I will try to update Python and see if that fixes it. Thank you for your time :)

**Comment by gjkf** [comment]
Can confirm: after having updated Python to the latest version (3.8.6) and having discover installed again using the updated `pip` command, no issue is risen.

I also tried to run the above commands you suggested and they all produce the expected output, no errors on their part.
I guess that fixes it, in case it comes up again, just update Python.

Thank you for your time and patience.

**Comment by trigg** [comment]
No problems! Glad you have it working

**Comment by Mxtreme1** [comment]
Have the same issue, after updating to python3.8
