### ISSUE TITLE
Tags in the text overlay

### ISSUE THREAD

**Issue by gjkf** [trigg/Discover#59]
Whenever there's any kind of tag (either a user or a role), the tag does not show the correct name, but the id, as follows

![image](https://user-images.githubusercontent.com/8215189/94943000-5fffa000-04d7-11eb-8539-a069f9125221.png)

This is what is supposed to be showed:

![image](https://user-images.githubusercontent.com/8215189/94943240-ac4ae000-04d7-11eb-8269-7a942ad5316b.png)

**Comment by trigg** [comment]
Thanks for the report, I forgot to put a bug report in for this. I'm currently working on a huge segment to get tags, formatting, images etc into text overlay.
