### ISSUE TITLE
How to set compositor?

### ISSUE THREAD

**Issue by Morantxu** [trigg/Discover#74]
Hey, the overlay works great, but because of picom, the background is blurry, how can I fix that ? In other apps, using class_g="firefox" for example solved the issue but class_g="discover-overlay" doesn't work here. Any clue?

**Comment by johnvictorfs** [comment]
```ini
blur-background-exclude = [
    "name *= 'discover-overlay'",
];
```

This worked for me with picom and i3wm

**Comment by Morantxu** [comment]
Thanks ! It worked like a charm :)

**Comment by papuSpartan** [comment]
This worked more reliably for me on BSPWM:
```
blur-background-exclude = [
       "class_g = 'Discover-overlay'"
];
```
