### ISSUE TITLE
Autostart on boot... doesn't?

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#76]
Using Manjaro & the latest build. Autostart is ticked, but I'm having to start it manually. It's even in my list of start up applications.
![Screenshot from 2020-10-06 17-34-24](https://user-images.githubusercontent.com/964775/95230807-3e195c80-07fa-11eb-82a9-eaa42b1abd39.png)

**Comment by trigg** [comment]
Attempt running the overlay from application menu instead of terminal.

**Comment by midget3111** [comment]
Didn't make a difference. A fresh install did though.

**Comment by midget3111** [comment]
This bug is once again at large. Using Murmur on Cinnamon

**Comment by pegasusearl** [comment]
hello there. Same problem here. Manjaro.


It's not like it does not run at all. It runs briefly then close immediately.
Here is the output
```
INFO:root:Loading saved channel 724965476651892790
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 724965476651892790
ERROR:root:Unable to read https://cdn.discordapp.com/embed/avatars/3.png
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Autostart info : desktop /usr/share/applications/discover_overlay.desktop auto None
ERROR:root:[Errno 111] Connection refused
INFO:root:Unable to connect to Discord client
```

**Comment by MurdoMaclachlan** [comment]
Sounds like it might be related to sone kind of initialisation failure. If the output says it's trying to load saved channels, then it's probably failing on that because the account isn't logged in yet so none of the channels will be available.

**Comment by trigg** [comment]
Very interesting findings! Thanks for hunting this down as I'd had no luck reproducing it.

**Comment by midget3111** [comment]
Glad to see  I'm not going crazy.

**Comment by yaomtc** [comment]
Also been happening with me on Arch Linux with Plasma.

**Comment by midget3111** [comment]
Still present in latest. Seems to not be saving its state?

**Comment by midget3111** [comment]
So, it turns out it does work and Autostarts on boot... the issue seems to be that when discord launches it crashes Discover-Overlay

**Comment by MurdoMaclachlan** [comment]
I've been trying to pin down the source of this, and it's consistently happenening when I run Discover first, then open Discord. Discover will complain that it couldn't connect to Discord, hang, then close once I open Discord.

After I added some extra logging, it seems that once Discord opens, Discover runs do_read() about 30-40 more times before it dies. It looks like it might be correlating with Discord finishing loading? It always seems to die a moment before Discord finishes loading.

Additionally, very occasionally it just succeeds and I can't work out why. It doesn't seem to matter how long or short the gap between running Discover/Discord is.

I recorded [a video](https://www.youtube.com/watch?v=wWY9ooWTh3I) (unlisted YouTube link since it's >10MB) of a few attempts with it crashing and one with it succeeding (couldn't get more than one; it's rare) to see if that helps anyone spot what's actually wrong.

**Comment by midget3111** [comment]
> I've been trying to pin down the source of this, and it's consistently happenening when I run Discover first, then open Discord. Discover will complain that it couldn't connect to Discord, hang, then close once I open Discord.
> 
> After I added some extra logging, it seems that once Discord opens, Discover runs do_read() about 30-40 more times before it dies. It looks like it might be correlating with Discord finishing loading? It always seems to die a moment before Discord finishes loading.
> 
> Additionally, very occasionally it just succeeds and I can't work out why. It doesn't seem to matter how long or short the gap between running Discover/Discord is.
> 
> I recorded [a video](https://www.youtube.com/watch?v=wWY9ooWTh3I) (unlisted YouTube link since it's >10MB) of a few attempts with it crashing and one with it succeeding (couldn't get more than one; it's rare) to see if that helps anyone spot what's actually wrong.

Can confirm, this is the exact same behaviour that I am seeing.

**Comment by midget3111** [comment]
> I've been trying to pin down the source of this, and it's consistently happenening when I run Discover first, then open Discord. Discover will complain that it couldn't connect to Discord, hang, then close once I open Discord.
> 
> After I added some extra logging, it seems that once Discord opens, Discover runs do_read() about 30-40 more times before it dies. It looks like it might be correlating with Discord finishing loading? It always seems to die a moment before Discord finishes loading.
> 
> Additionally, very occasionally it just succeeds and I can't work out why. It doesn't seem to matter how long or short the gap between running Discover/Discord is.
> 
> I recorded [a video](https://www.youtube.com/watch?v=wWY9ooWTh3I) (unlisted YouTube link since it's >10MB) of a few attempts with it crashing and one with it succeeding (couldn't get more than one; it's rare) to see if that helps anyone spot what's actually wrong.

After a bit of research, seems to be a json response error. Annoyingly, my setup has stopped doing it halfway through testing and is now working as expected. Will see how long that lasts for!

**Comment by midget3111** [comment]
Also fixed! closing.
