### ISSUE TITLE
Issue with positioning while using fractional scaling

### ISSUE THREAD

**Issue by emujoyce** [trigg/Discover#77]
Line 80 of overlay.py and line 53 of draggable_window.py both use `get_scale_factor()` which returns an int. When the scale factor is 1.5 this breaks entirely. I know theres nothing you can do since the suggested alternative `Gdk.Window.get_scale_factor` is also an int. Maybe this can be will be adjusted in a future update?

**Comment by trigg** [comment]
I've actually not seen fractional scaling anywhere yet. What setup do you use that has it?

**Comment by emujoyce** [comment]
Pop OS just released it as an option. Its been around for a while as a feature one could enable but not as trivial as single click.
`Shell: bash 5.0.17 
Resolution: 5120x2880
DE: GNOME 
WM: Mutter 
`

**Comment by trigg** [comment]
I will see where the land lays on this in wayland environments since fractional scaling appears to have some maturity there. For X11 I won't be planning anything here
