### ISSUE TITLE
[Feature] Display nickname instead of account name

### ISSUE THREAD

**Issue by Estrozix** [trigg/Discover#83]
Would be useful if you could choose to display the nickname of people instead of their account name. 
Especially useful in discord servers that have special naming conventions, for example having your nickname match your character name in a game.
Not sure if this is technically possible but would help out a lot.

**Comment by trigg** [comment]
I thought we did! Where are you seeing account names when a nickname is set?

**Comment by Estrozix** [comment]
In the overlay when people are talking. Maybe I have it set up incorrectly.

**Comment by Estrozix** [comment]
Nevermind, I installed the latest testing version and I now see the nicknames instead. Sorry for not checking this in advance.

**Comment by trigg** [comment]
No worries! :)
