### ISSUE TITLE
New milestones

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#84]
We need to decide on future milestones.
What features are missing?
Is the current code clean?
Where should the project be heading?

**Comment by GregTheMadMonk** [comment]
Not a feature or anything but maybe text/voice/general settings should be just a tabs in a single settings window?

**Comment by trigg** [comment]
> Not a feature or anything but maybe text/voice/general settings should be just a tabs in a single settings window?

That's a much better idea
