### ISSUE TITLE
Add option to use nicknames instead of usernames

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#91]

**Comment by trigg** [comment]
Care to elaborate?

**Comment by midget3111** [comment]
Fairly sure nicknames are the default in the later versions?

**Comment by trigg** [comment]
Duplicate of #83

**Comment by Joshix-1** [comment]
The I'm stupid.
![image](https://user-images.githubusercontent.com/57299889/96475053-da4c5600-1233-11eb-9701-e8f862c3ccc5.png)

**Comment by trigg** [comment]
Are you on stable or latest?

**Comment by Joshix-1** [comment]
I'm on stable. The chat uses nicknames.

**Comment by trigg** [comment]
Fixed in latest, doing a push towards new stable 0.3.0 soon
