### ISSUE TITLE
Interference with right-click and dragging ability on cinnamon panel on Linux Mint 20 Cinnamon

### ISSUE THREAD

**Issue by forever-and-a-day** [trigg/Discover#98]
When discover overlay is active, you are unable to right click empty space in the panel and get the context menu. In addition, dragging pinned applications does not rearrange them while the discover overlay is running. 
Video demonstration if that's easier for ya: https://www.youtube.com/watch?v=UmmEyW3VomI

**Comment by midget3111** [comment]
Interesting! Also probably one of the better bug reports I've seen so far.
If possible, would you be able to run it from a terminal and see if you get any errors?
In the mean time, one of us will give it a try with Cinnamon!

**Comment by midget3111** [comment]
Okay, in Discover settings rather than using "Anchor to edge", could you try "Floating"? that should fix it

**Comment by trigg** [comment]
I have just installed Cinnamon to check this out. For some reason the panel believes you are interacting with the (invisible) overlay above it. So Drag believes it's dropping onto the overlay and right clicking believes it's the overlay.

These are both incorrect as the XShape input shape should be fixing that. 

As @midget3111 has said, Use floating and make sure the window doesn't coincide with the panel.

**Comment by forever-and-a-day** [comment]
Awesome - That works! Thanks!
